//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type dimensionTypeJSON struct {
	FixedTime                *int64  `json:"fixed_time,omitempty"`
	HasSkylight              bool    `json:"has_skylight"`
	HasCeiling               bool    `json:"has_ceiling"`
	Ultrawarm                bool    `json:"ultrawarm"`
	Natural                  bool    `json:"natural"`
	CoordinateScale          float64 `json:"coordinate_scale"`
	BedWorks                 bool    `json:"bed_works"`
	RespawnAnchorWorks       bool    `json:"respawn_anchor_works"`
	MinY                     int     `json:"min_y"`
	Height                   int     `json:"height"`
	LogicalHeight            int     `json:"logical_height"`
	Infiniburn               string  `json:"infiniburn"`
	Effects                  string  `json:"effects"`
	AmbientLight             float64 `json:"ambient_light"`
	PiglinSafe               bool    `json:"piglin_safe"`
	HasRaids                 bool    `json:"has_raids"`
	MonsterSpawnLightLevel   any     `json:"monster_spawn_light_level"`
	MonsterSpawnBlockLightLimit int  `json:"monster_spawn_block_light_limit"`
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	datapackDir := filepath.Join(projectRoot, ".mcdata", *version, "datapacks", "dimension_type")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "dimension", "dimensions.go")

	entries, err := os.ReadDir(datapackDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read dimension_type dir: %v\n", err)
		os.Exit(1)
	}

	type dimEntry struct {
		Name          string
		HasSkylight   bool
		HasCeiling    bool
		Natural       bool
		MinY          int
		Height        int
		LogicalHeight int
		AmbientLight  float64
	}

	var dimensions []dimEntry
	for _, entry := range entries {
		if !strings.HasSuffix(entry.Name(), ".json") {
			continue
		}

		data, err := os.ReadFile(filepath.Join(datapackDir, entry.Name()))
		if err != nil {
			continue
		}

		var dt dimensionTypeJSON
		if err := json.Unmarshal(data, &dt); err != nil {
			continue
		}

		name := "minecraft:" + strings.TrimSuffix(entry.Name(), ".json")
		dimensions = append(dimensions, dimEntry{
			Name:          name,
			HasSkylight:   dt.HasSkylight,
			HasCeiling:    dt.HasCeiling,
			Natural:       dt.Natural,
			MinY:          dt.MinY,
			Height:        dt.Height,
			LogicalHeight: dt.LogicalHeight,
			AmbientLight:  dt.AmbientLight,
		})
	}

	sort.Slice(dimensions, func(i, j int) bool {
		return dimensions[i].Name < dimensions[j].Name
	})

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/dimension; DO NOT EDIT.\n\n")
	buf.WriteString("package dimension\n\n")

	buf.WriteString("type DimensionInfo struct {\n")
	buf.WriteString("\tID            int32\n")
	buf.WriteString("\tName          string\n")
	buf.WriteString("\tHasSkylight   bool\n")
	buf.WriteString("\tHasCeiling    bool\n")
	buf.WriteString("\tNatural       bool\n")
	buf.WriteString("\tMinY          int32\n")
	buf.WriteString("\tHeight        int32\n")
	buf.WriteString("\tLogicalHeight int32\n")
	buf.WriteString("\tAmbientLight  float64\n")
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("const DimensionCount = %d\n\n", len(dimensions)))

	buf.WriteString("var Dimensions = []DimensionInfo{\n")
	for i, d := range dimensions {
		buf.WriteString(fmt.Sprintf("\t{ID: %d, Name: %q, HasSkylight: %v, HasCeiling: %v, Natural: %v, MinY: %d, Height: %d, LogicalHeight: %d, AmbientLight: %v},\n",
			i, d.Name, d.HasSkylight, d.HasCeiling, d.Natural, d.MinY, d.Height, d.LogicalHeight, d.AmbientLight))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var dimensionByName = map[string]int32{\n")
	for i, d := range dimensions {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", d.Name, i))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func DimensionIDByName(name string) int32 {
	if id, ok := dimensionByName[name]; ok {
		return id
	}
	return -1
}

func DimensionByID(id int32) *DimensionInfo {
	if id < 0 || int(id) >= len(Dimensions) {
		return nil
	}
	return &Dimensions[id]
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d dimensions)\n", outputFile, len(dimensions))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}
