//go:build ignore

package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

type brewingRecipe struct {
	Input      string
	Ingredient string
	Output     string
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	javaFile := filepath.Join(projectRoot, ".mc-decompiled", *version+"-decompiled", "net", "minecraft", "world", "item", "alchemy", "PotionBrewing.java")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "potion_brewing", "recipes.go")

	recipes, err := parsePotionBrewingJava(javaFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse PotionBrewing.java: %v\n", err)
		os.Exit(1)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/potion_brewing; DO NOT EDIT.\n\n")
	buf.WriteString("package potionbrewing\n\n")

	buf.WriteString(fmt.Sprintf("const BrewingRecipeCount = %d\n\n", len(recipes)))

	buf.WriteString("type BrewingRecipe struct {\n")
	buf.WriteString("\tInput      string\n")
	buf.WriteString("\tIngredient string\n")
	buf.WriteString("\tOutput     string\n")
	buf.WriteString("}\n\n")

	buf.WriteString("var BrewingRecipes = []BrewingRecipe{\n")
	for _, r := range recipes {
		buf.WriteString(fmt.Sprintf("\t{Input: %q, Ingredient: %q, Output: %q},\n", r.Input, r.Ingredient, r.Output))
	}
	buf.WriteString("}\n")

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d brewing recipes)\n", outputFile, len(recipes))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func parsePotionBrewingJava(javaFile string) ([]brewingRecipe, error) {
	content, err := os.ReadFile(javaFile)
	if err != nil {
		return nil, err
	}

	// Match: addMix(Potions.WATER, Items.NETHER_WART, Potions.AWKWARD);
	pattern := regexp.MustCompile(`addMix\(Potions\.(\w+), Items\.(\w+), Potions\.(\w+)\);`)
	var recipes []brewingRecipe

	for _, match := range pattern.FindAllStringSubmatch(string(content), -1) {
		if len(match) > 3 {
			recipes = append(recipes, brewingRecipe{
				Input:      "minecraft:" + strings.ToLower(match[1]),
				Ingredient: "minecraft:" + strings.ToLower(match[2]),
				Output:     "minecraft:" + strings.ToLower(match[3]),
			})
		}
	}

	return recipes, nil
}
