//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type trimPatternJSON struct {
	AssetID     string `json:"asset_id"`
	TemplateItem string `json:"template_item"`
	Decal       bool   `json:"decal"`
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	datapackDir := filepath.Join(projectRoot, ".mcdata", *version, "datapacks", "trim_pattern")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "trim_pattern", "trim_patterns.go")

	entries, err := os.ReadDir(datapackDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read trim_pattern dir: %v\n", err)
		os.Exit(1)
	}

	type patternEntry struct {
		Name         string
		AssetID      string
		TemplateItem string
	}

	var patterns []patternEntry
	for _, entry := range entries {
		if !strings.HasSuffix(entry.Name(), ".json") {
			continue
		}

		data, err := os.ReadFile(filepath.Join(datapackDir, entry.Name()))
		if err != nil {
			continue
		}

		var p trimPatternJSON
		if err := json.Unmarshal(data, &p); err != nil {
			continue
		}

		name := "minecraft:" + strings.TrimSuffix(entry.Name(), ".json")
		patterns = append(patterns, patternEntry{
			Name:         name,
			AssetID:      p.AssetID,
			TemplateItem: p.TemplateItem,
		})
	}

	sort.Slice(patterns, func(i, j int) bool {
		return patterns[i].Name < patterns[j].Name
	})

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/trim_pattern; DO NOT EDIT.\n\n")
	buf.WriteString("package trimpattern\n\n")

	buf.WriteString("type TrimPatternInfo struct {\n")
	buf.WriteString("\tID           int32\n")
	buf.WriteString("\tName         string\n")
	buf.WriteString("\tAssetID      string\n")
	buf.WriteString("\tTemplateItem string\n")
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("const TrimPatternCount = %d\n\n", len(patterns)))

	buf.WriteString("var TrimPatterns = []TrimPatternInfo{\n")
	for i, p := range patterns {
		buf.WriteString(fmt.Sprintf("\t{ID: %d, Name: %q, AssetID: %q, TemplateItem: %q},\n",
			i, p.Name, p.AssetID, p.TemplateItem))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var trimPatternByName = map[string]int32{\n")
	for i, p := range patterns {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", p.Name, i))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func TrimPatternIDByName(name string) int32 {
	if id, ok := trimPatternByName[name]; ok {
		return id
	}
	return -1
}

func TrimPatternByID(id int32) *TrimPatternInfo {
	if id < 0 || int(id) >= len(TrimPatterns) {
		return nil
	}
	return &TrimPatterns[id]
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d trim patterns)\n", outputFile, len(patterns))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}
