//go:build ignore

package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

type compostEntry struct {
	Item   string
	Chance float32
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	javaFile := filepath.Join(projectRoot, ".mc-decompiled", *version+"-decompiled", "net", "minecraft", "world", "level", "block", "ComposterBlock.java")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "composter", "compostables.go")

	entries, err := parseComposterJava(javaFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse ComposterBlock.java: %v\n", err)
		os.Exit(1)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/composter; DO NOT EDIT.\n\n")
	buf.WriteString("package composter\n\n")

	buf.WriteString(fmt.Sprintf("const CompostableCount = %d\n\n", len(entries)))

	buf.WriteString("var Compostables = map[string]float32{\n")
	for _, e := range entries {
		buf.WriteString(fmt.Sprintf("\t%q: %v,\n", e.Item, e.Chance))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func GetCompostChance(item string) float32 {
	if chance, ok := Compostables[item]; ok {
		return chance
	}
	return -1
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d compostables)\n", outputFile, len(entries))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func parseComposterJava(javaFile string) ([]compostEntry, error) {
	content, err := os.ReadFile(javaFile)
	if err != nil {
		return nil, err
	}

	// Match: add(0.3F, Items.JUNGLE_LEAVES);
	pattern := regexp.MustCompile(`add\(([0-9.]+)F?, Items\.(\w+)\);`)
	var entries []compostEntry

	for _, match := range pattern.FindAllStringSubmatch(string(content), -1) {
		if len(match) > 2 {
			var chance float32
			fmt.Sscanf(match[1], "%f", &chance)
			item := "minecraft:" + strings.ToLower(match[2])
			entries = append(entries, compostEntry{Item: item, Chance: chance})
		}
	}

	return entries, nil
}
