//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

type blockJSON struct {
	ID           int32       `json:"id"`
	Name         string      `json:"name"`
	Hardness     float64     `json:"hardness"`
	Resistance   float64     `json:"resistance"`
	Transparent  bool        `json:"transparent"`
	EmitLight    int32       `json:"emitLight"`
	FilterLight  int32       `json:"filterLight"`
	DefaultState int32       `json:"defaultState"`
	MinStateID   int32       `json:"minStateId"`
	MaxStateID   int32       `json:"maxStateId"`
	States       []stateJSON `json:"states"`
	BoundingBox  string      `json:"boundingBox"`
}

type stateJSON struct {
	Name      string   `json:"name"`
	Type      string   `json:"type"`
	NumValues int      `json:"num_values"`
	Values    []string `json:"values"`
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	inputFile := filepath.Join(projectRoot, ".mcdata", *version, "blocks.json")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "block", "blocks.go")

	data, err := os.ReadFile(inputFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read blocks.json: %v\n", err)
		os.Exit(1)
	}

	var blocks []blockJSON
	if err := json.Unmarshal(data, &blocks); err != nil {
		fmt.Fprintf(os.Stderr, "parse blocks.json: %v\n", err)
		os.Exit(1)
	}

	maxStateID := int32(0)
	for _, b := range blocks {
		if b.MaxStateID > maxStateID {
			maxStateID = b.MaxStateID
		}
	}

	var buf strings.Builder

	buf.WriteString("// Code generated by internal/data/generator/block; DO NOT EDIT.\n\n")
	buf.WriteString("package block\n\n")

	writeBlockInfoTable(&buf, blocks)
	writeStateToBlockTable(&buf, blocks, maxStateID)
	writePropertyTables(&buf, blocks)

	source := buf.String()
	formatted, err := format.Source([]byte(source))
	if err != nil {
		fmt.Fprintf(os.Stderr, "gofmt: %v\nwriting unformatted\n", err)
		formatted = []byte(source)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write output: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d blocks, %d states)\n", outputFile, len(blocks), maxStateID+1)
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func writeBlockInfoTable(buf *strings.Builder, blocks []blockJSON) {
	buf.WriteString("type BlockInfo struct {\n")
	buf.WriteString("\tID           int32\n")
	buf.WriteString("\tName         string\n")
	buf.WriteString("\tMinStateID   int32\n")
	buf.WriteString("\tMaxStateID   int32\n")
	buf.WriteString("\tDefaultState int32\n")
	buf.WriteString("\tTransparent  bool\n")
	buf.WriteString("\tFilterLight  int32\n")
	buf.WriteString("\tEmitLight    int32\n")
	buf.WriteString("\tHardness     float64\n")
	buf.WriteString("\tResistance   float64\n")
	buf.WriteString("\tSolid        bool\n")
	buf.WriteString("\tProperties   []PropertyDef\n")
	buf.WriteString("}\n\n")

	buf.WriteString("type PropertyDef struct {\n")
	buf.WriteString("\tName   string\n")
	buf.WriteString("\tValues []string\n")
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("const BlockCount = %d\n\n", len(blocks)))

	buf.WriteString("var Blocks = [...]BlockInfo{\n")
	for _, b := range blocks {
		solid := b.BoundingBox == "block"
		buf.WriteString(fmt.Sprintf("\t{ID: %d, Name: %q, MinStateID: %d, MaxStateID: %d, DefaultState: %d, Transparent: %v, FilterLight: %d, EmitLight: %d, Hardness: %v, Resistance: %v, Solid: %v",
			b.ID, "minecraft:"+b.Name, b.MinStateID, b.MaxStateID, b.DefaultState, b.Transparent, b.FilterLight, b.EmitLight, b.Hardness, b.Resistance, solid))
		if len(b.States) > 0 {
			buf.WriteString(", Properties: []PropertyDef{")
			for i, s := range b.States {
				if i > 0 {
					buf.WriteString(", ")
				}
				vals := s.Values
				if s.Type == "bool" {
					vals = []string{"true", "false"}
				}
				buf.WriteString(fmt.Sprintf("{Name: %q, Values: []string{", s.Name))
				for j, v := range vals {
					if j > 0 {
						buf.WriteString(", ")
					}
					buf.WriteString(fmt.Sprintf("%q", v))
				}
				buf.WriteString("}}")
			}
			buf.WriteString("}")
		}
		buf.WriteString("},\n")
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var BlockByName = map[string]int32{\n")
	for _, b := range blocks {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", "minecraft:"+b.Name, b.ID))
	}
	buf.WriteString("}\n\n")
}

func writeStateToBlockTable(buf *strings.Builder, blocks []blockJSON, maxStateID int32) {
	buf.WriteString(fmt.Sprintf("const TotalStates = %d\n\n", maxStateID+1))

	buf.WriteString(fmt.Sprintf("var StateToBlock = [%d]int32{\n", maxStateID+1))

	stateToBlock := make([]int32, maxStateID+1)
	for _, b := range blocks {
		for sid := b.MinStateID; sid <= b.MaxStateID; sid++ {
			stateToBlock[sid] = b.ID
		}
	}

	for i := int32(0); i <= maxStateID; i++ {
		if i > 0 && i%20 == 0 {
			buf.WriteString("\n\t")
		} else if i%20 == 0 {
			buf.WriteString("\t")
		}
		buf.WriteString(fmt.Sprintf("%d, ", stateToBlock[i]))
	}
	buf.WriteString("\n}\n\n")
}

func writePropertyTables(buf *strings.Builder, blocks []blockJSON) {
	for _, b := range blocks {
		if b.Name == "air" {
			buf.WriteString(fmt.Sprintf("const AirStateID = %d\n\n", b.DefaultState))
			break
		}
	}

	important := []string{
		"air", "stone", "granite", "diorite", "andesite",
		"grass_block", "dirt", "coarse_dirt", "cobblestone",
		"oak_planks", "spruce_planks", "birch_planks",
		"bedrock", "water", "lava",
		"sand", "gravel", "gold_ore", "iron_ore", "coal_ore",
		"oak_log", "spruce_log", "birch_log",
		"oak_leaves", "spruce_leaves", "birch_leaves",
		"glass", "diamond_ore", "diamond_block",
		"crafting_table", "furnace",
		"obsidian", "torch",
		"chest", "redstone_ore",
		"snow_block", "ice",
		"clay", "netherrack", "glowstone",
		"oak_stairs", "stone_stairs",
		"oak_slab", "stone_slab",
		"tall_grass", "short_grass",
		"oak_fence", "oak_door",
		"deepslate", "copper_ore",
	}

	buf.WriteString("const (\n")
	for _, name := range important {
		for _, b := range blocks {
			if b.Name == name {
				constName := snakeToPascal(name) + "DefaultState"
				buf.WriteString(fmt.Sprintf("\t%s int32 = %d\n", constName, b.DefaultState))
				break
			}
		}
	}
	buf.WriteString(")\n")
}

func snakeToPascal(s string) string {
	parts := strings.Split(s, "_")
	var result strings.Builder
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		result.WriteString(strings.ToUpper(p[:1]))
		result.WriteString(p[1:])
	}
	return result.String()
}
