//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

type soundJSON struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	inputFile := filepath.Join(projectRoot, ".mcdata", *version, "sounds.json")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "sound", "sounds.go")

	data, err := os.ReadFile(inputFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read sounds.json: %v\n", err)
		os.Exit(1)
	}

	var sounds []soundJSON
	if err := json.Unmarshal(data, &sounds); err != nil {
		fmt.Fprintf(os.Stderr, "parse sounds.json: %v\n", err)
		os.Exit(1)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/sound; DO NOT EDIT.\n\n")
	buf.WriteString("package sound\n\n")

	buf.WriteString(fmt.Sprintf("const SoundCount = %d\n\n", len(sounds)))

	buf.WriteString("var SoundNames = []string{\n")
	for _, s := range sounds {
		buf.WriteString(fmt.Sprintf("\t%q, // %d\n", s.Name, s.ID))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var soundByName = map[string]int32{\n")
	for _, s := range sounds {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", s.Name, s.ID))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func SoundIDByName(name string) int32 {
	if id, ok := soundByName[name]; ok {
		return id
	}
	return -1
}

func SoundNameByID(id int32) string {
	if id < 0 || int(id) >= len(SoundNames) {
		return ""
	}
	return SoundNames[id]
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d sounds)\n", outputFile, len(sounds))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}
