//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type collisionJSON struct {
	Blocks map[string]json.RawMessage `json:"blocks"`
	Shapes map[string]json.RawMessage `json:"shapes"`
}

type blockJSON struct {
	ID         int32  `json:"id"`
	Name       string `json:"name"`
	MinStateID int32  `json:"minStateId"`
	MaxStateID int32  `json:"maxStateId"`
}

type aabb struct {
	MinX, MinY, MinZ float64
	MaxX, MaxY, MaxZ float64
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	collisionFile := filepath.Join(projectRoot, ".mcdata", *version, "blockCollisionShapes.json")
	blocksFile := filepath.Join(projectRoot, ".mcdata", *version, "blocks.json")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "collision", "shapes.go")

	collisionData, err := os.ReadFile(collisionFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read blockCollisionShapes.json: %v\n", err)
		os.Exit(1)
	}

	blocksData, err := os.ReadFile(blocksFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read blocks.json: %v\n", err)
		os.Exit(1)
	}

	var collision collisionJSON
	if err := json.Unmarshal(collisionData, &collision); err != nil {
		fmt.Fprintf(os.Stderr, "parse blockCollisionShapes.json: %v\n", err)
		os.Exit(1)
	}

	var blocks []blockJSON
	if err := json.Unmarshal(blocksData, &blocks); err != nil {
		fmt.Fprintf(os.Stderr, "parse blocks.json: %v\n", err)
		os.Exit(1)
	}

	blockByName := make(map[string]*blockJSON, len(blocks))
	for i := range blocks {
		blockByName[blocks[i].Name] = &blocks[i]
	}

	shapes := parseShapes(collision.Shapes)

	var maxStateID int32
	for _, b := range blocks {
		if b.MaxStateID > maxStateID {
			maxStateID = b.MaxStateID
		}
	}

	stateToShape := make([]int32, maxStateID+1)
	for i := range stateToShape {
		stateToShape[i] = 0
	}

	for blockName, raw := range collision.Blocks {
		blk, ok := blockByName[blockName]
		if !ok {
			continue
		}

		var singleIdx float64
		if err := json.Unmarshal(raw, &singleIdx); err == nil {
			shapeIdx := int32(singleIdx)
			for sid := blk.MinStateID; sid <= blk.MaxStateID; sid++ {
				stateToShape[sid] = shapeIdx
			}
			continue
		}

		var idxArray []float64
		if err := json.Unmarshal(raw, &idxArray); err == nil {
			stateCount := blk.MaxStateID - blk.MinStateID + 1
			for i := int32(0); i < stateCount && i < int32(len(idxArray)); i++ {
				stateToShape[blk.MinStateID+i] = int32(idxArray[i])
			}
		}
	}

	code := generateCode(shapes, stateToShape)

	formatted, err := format.Source([]byte(code))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\nsource:\n%s\n", err, code[:min(len(code), 2000)])
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d shapes, %d state mappings)\n", outputFile, len(shapes), len(stateToShape))
}

func parseShapes(raw map[string]json.RawMessage) map[int32][]aabb {
	result := make(map[int32][]aabb, len(raw))
	for key, val := range raw {
		idx, err := strconv.Atoi(key)
		if err != nil {
			continue
		}

		var rawBoxes [][]float64
		if err := json.Unmarshal(val, &rawBoxes); err != nil {
			continue
		}

		boxes := make([]aabb, 0, len(rawBoxes))
		for _, b := range rawBoxes {
			if len(b) != 6 {
				continue
			}
			boxes = append(boxes, aabb{
				MinX: b[0], MinY: b[1], MinZ: b[2],
				MaxX: b[3], MaxY: b[4], MaxZ: b[5],
			})
		}
		result[int32(idx)] = boxes
	}
	return result
}

func generateCode(shapes map[int32][]aabb, stateToShape []int32) string {
	var buf strings.Builder

	buf.WriteString("// Code generated by internal/data/generator/collision/shapes; DO NOT EDIT.\n\n")
	buf.WriteString("package collision\n\n")

	buf.WriteString("type AABB struct {\n")
	buf.WriteString("\tMinX, MinY, MinZ float64\n")
	buf.WriteString("\tMaxX, MaxY, MaxZ float64\n")
	buf.WriteString("}\n\n")

	sortedKeys := make([]int32, 0, len(shapes))
	for k := range shapes {
		sortedKeys = append(sortedKeys, k)
	}
	sort.Slice(sortedKeys, func(i, j int) bool { return sortedKeys[i] < sortedKeys[j] })

	buf.WriteString(fmt.Sprintf("const ShapeCount = %d\n\n", len(shapes)))
	buf.WriteString(fmt.Sprintf("const TotalStates = %d\n\n", len(stateToShape)))

	buf.WriteString("var Shapes = map[int32][]AABB{\n")
	for _, k := range sortedKeys {
		boxes := shapes[k]
		if len(boxes) == 0 {
			buf.WriteString(fmt.Sprintf("\t%d: {},\n", k))
		} else {
			buf.WriteString(fmt.Sprintf("\t%d: {\n", k))
			for _, b := range boxes {
				buf.WriteString(fmt.Sprintf("\t\t{MinX: %s, MinY: %s, MinZ: %s, MaxX: %s, MaxY: %s, MaxZ: %s},\n",
					fmtFloat(b.MinX), fmtFloat(b.MinY), fmtFloat(b.MinZ),
					fmtFloat(b.MaxX), fmtFloat(b.MaxY), fmtFloat(b.MaxZ)))
			}
			buf.WriteString("\t},\n")
		}
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var StateToShapeIndex = [...]int32{\n")
	const perLine = 20
	for i := 0; i < len(stateToShape); i += perLine {
		buf.WriteString("\t")
		end := i + perLine
		if end > len(stateToShape) {
			end = len(stateToShape)
		}
		for j := i; j < end; j++ {
			if j > i {
				buf.WriteString(", ")
			}
			buf.WriteString(strconv.Itoa(int(stateToShape[j])))
		}
		buf.WriteString(",\n")
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func ShapesForStateID(stateID int32) []AABB {
	if stateID < 0 || stateID >= int32(len(StateToShapeIndex)) {
		return nil
	}
	return Shapes[StateToShapeIndex[stateID]]
}

func IsEmpty(stateID int32) bool {
	if stateID < 0 || stateID >= int32(len(StateToShapeIndex)) {
		return true
	}
	return len(Shapes[StateToShapeIndex[stateID]]) == 0
}

func IsFullBlock(stateID int32) bool {
	if stateID < 0 || stateID >= int32(len(StateToShapeIndex)) {
		return false
	}
	boxes := Shapes[StateToShapeIndex[stateID]]
	if len(boxes) != 1 {
		return false
	}
	b := boxes[0]
	return b.MinX == 0 && b.MinY == 0 && b.MinZ == 0 &&
		b.MaxX == 1 && b.MaxY == 1 && b.MaxZ == 1
}
`)

	return buf.String()
}

func fmtFloat(f float64) string {
	if f == float64(int64(f)) {
		return fmt.Sprintf("%.1f", f)
	}
	return strconv.FormatFloat(f, 'f', -1, 64)
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}
