//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type biomeJSON struct {
	ID          int     `json:"id"`
	Name        string  `json:"name"`
	Category    string  `json:"category"`
	Temperature float64 `json:"temperature"`
	Precipitation string `json:"precipitation"`
	Depth       float64 `json:"depth"`
	Dimension   string  `json:"dimension"`
	DisplayName string  `json:"displayName"`
	Color       int     `json:"color"`
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	inputFile := filepath.Join(projectRoot, ".mcdata", *version, "biomes.json")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "biome", "biomes.go")

	data, err := os.ReadFile(inputFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read biomes.json: %v\n", err)
		os.Exit(1)
	}

	var biomes []biomeJSON
	if err := json.Unmarshal(data, &biomes); err != nil {
		fmt.Fprintf(os.Stderr, "parse biomes.json: %v\n", err)
		os.Exit(1)
	}

	sort.Slice(biomes, func(i, j int) bool {
		return biomes[i].ID < biomes[j].ID
	})

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/biome; DO NOT EDIT.\n\n")
	buf.WriteString("package biome\n\n")

	buf.WriteString("type BiomeInfo struct {\n")
	buf.WriteString("\tID          int32\n")
	buf.WriteString("\tName        string\n")
	buf.WriteString("\tCategory    string\n")
	buf.WriteString("\tTemperature float64\n")
	buf.WriteString("\tColor       int32\n")
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("const BiomeCount = %d\n\n", len(biomes)))

	buf.WriteString("const (\n")
	for _, b := range biomes {
		constName := toConstName(b.Name)
		buf.WriteString(fmt.Sprintf("\tBiome%s int32 = %d\n", constName, b.ID))
	}
	buf.WriteString(")\n\n")

	buf.WriteString("var Biomes = []BiomeInfo{\n")
	for _, b := range biomes {
		buf.WriteString(fmt.Sprintf("\t{ID: %d, Name: %q, Category: %q, Temperature: %v, Color: %d},\n",
			b.ID, "minecraft:"+b.Name, b.Category, b.Temperature, b.Color))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var biomeByName = map[string]int32{\n")
	for _, b := range biomes {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", "minecraft:"+b.Name, b.ID))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func BiomeIDByName(name string) int32 {
	if id, ok := biomeByName[name]; ok {
		return id
	}
	return -1
}

func BiomeByID(id int32) *BiomeInfo {
	if id < 0 || int(id) >= len(Biomes) {
		return nil
	}
	return &Biomes[id]
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d biomes)\n", outputFile, len(biomes))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func toConstName(name string) string {
	parts := strings.Split(name, "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}
