// Code generated by "stringer -type ServerboundPacketID"; DO NOT EDIT.

package packetid

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServerboundLoginLoginStart-0]
	_ = x[ServerboundLoginEncryptionBegin-1]
	_ = x[ServerboundLoginLoginPluginResponse-2]
	_ = x[ServerboundLoginLoginAcknowledged-3]
	_ = x[ServerboundLoginCookieResponse-4]
	_ = x[ServerboundStatusPingStart-0]
	_ = x[ServerboundStatusPing-1]
	_ = x[ServerboundConfigSettings-0]
	_ = x[ServerboundConfigCookieResponse-1]
	_ = x[ServerboundConfigCustomPayload-2]
	_ = x[ServerboundConfigFinishConfiguration-3]
	_ = x[ServerboundConfigKeepAlive-4]
	_ = x[ServerboundConfigPong-5]
	_ = x[ServerboundConfigResourcePackReceive-6]
	_ = x[ServerboundConfigSelectKnownPacks-7]
	_ = x[ServerboundConfigCustomReportDetails-8]
	_ = x[ServerboundConfigServerLinks-9]
	_ = x[ServerboundTeleportConfirm-0]
	_ = x[ServerboundQueryBlockNbt-1]
	_ = x[ServerboundSelectBundleItem-2]
	_ = x[ServerboundSetDifficulty-3]
	_ = x[ServerboundMessageAcknowledgement-4]
	_ = x[ServerboundChatCommand-5]
	_ = x[ServerboundChatCommandSigned-6]
	_ = x[ServerboundChatMessage-7]
	_ = x[ServerboundChatSessionUpdate-8]
	_ = x[ServerboundChunkBatchReceived-9]
	_ = x[ServerboundClientCommand-10]
	_ = x[ServerboundTickEnd-11]
	_ = x[ServerboundSettings-12]
	_ = x[ServerboundTabComplete-13]
	_ = x[ServerboundConfigurationAcknowledged-14]
	_ = x[ServerboundEnchantItem-15]
	_ = x[ServerboundWindowClick-16]
	_ = x[ServerboundCloseWindow-17]
	_ = x[ServerboundSetSlotState-18]
	_ = x[ServerboundCookieResponse-19]
	_ = x[ServerboundCustomPayload-20]
	_ = x[ServerboundDebugSampleSubscription-21]
	_ = x[ServerboundEditBook-22]
	_ = x[ServerboundQueryEntityNbt-23]
	_ = x[ServerboundUseEntity-24]
	_ = x[ServerboundGenerateStructure-25]
	_ = x[ServerboundKeepAlive-26]
	_ = x[ServerboundLockDifficulty-27]
	_ = x[ServerboundPosition-28]
	_ = x[ServerboundPositionLook-29]
	_ = x[ServerboundLook-30]
	_ = x[ServerboundFlying-31]
	_ = x[ServerboundVehicleMove-32]
	_ = x[ServerboundSteerBoat-33]
	_ = x[ServerboundPickItemFromBlock-34]
	_ = x[ServerboundPickItemFromEntity-35]
	_ = x[ServerboundPingRequest-36]
	_ = x[ServerboundCraftRecipeRequest-37]
	_ = x[ServerboundAbilities-38]
	_ = x[ServerboundBlockDig-39]
	_ = x[ServerboundEntityAction-40]
	_ = x[ServerboundPlayerInput-41]
	_ = x[ServerboundPlayerLoaded-42]
	_ = x[ServerboundPong-43]
	_ = x[ServerboundRecipeBook-44]
	_ = x[ServerboundDisplayedRecipe-45]
	_ = x[ServerboundNameItem-46]
	_ = x[ServerboundResourcePackReceive-47]
	_ = x[ServerboundAdvancementTab-48]
	_ = x[ServerboundSelectTrade-49]
	_ = x[ServerboundSetBeaconEffect-50]
	_ = x[ServerboundHeldItemSlot-51]
	_ = x[ServerboundUpdateCommandBlock-52]
	_ = x[ServerboundUpdateCommandBlockMinecart-53]
	_ = x[ServerboundSetCreativeSlot-54]
	_ = x[ServerboundUpdateJigsawBlock-55]
	_ = x[ServerboundUpdateStructureBlock-56]
	_ = x[ServerboundUpdateSign-57]
	_ = x[ServerboundArmAnimation-58]
	_ = x[ServerboundSpectate-59]
	_ = x[ServerboundBlockPlace-60]
	_ = x[ServerboundUseItem-61]
	_ = x[ServerboundPacketIDGuard-2147483647]
}

const (
	_ServerboundPacketID_name_0 = "ServerboundLoginLoginStartServerboundLoginEncryptionBeginServerboundLoginLoginPluginResponseServerboundLoginLoginAcknowledgedServerboundLoginCookieResponseServerboundConfigPongServerboundConfigResourcePackReceiveServerboundConfigSelectKnownPacksServerboundConfigCustomReportDetailsServerboundConfigServerLinksServerboundClientCommandServerboundTickEndServerboundSettingsServerboundTabCompleteServerboundConfigurationAcknowledgedServerboundEnchantItemServerboundWindowClickServerboundCloseWindowServerboundSetSlotStateServerboundCookieResponseServerboundCustomPayloadServerboundDebugSampleSubscriptionServerboundEditBookServerboundQueryEntityNbtServerboundUseEntityServerboundGenerateStructureServerboundKeepAliveServerboundLockDifficultyServerboundPositionServerboundPositionLookServerboundLookServerboundFlyingServerboundVehicleMoveServerboundSteerBoatServerboundPickItemFromBlockServerboundPickItemFromEntityServerboundPingRequestServerboundCraftRecipeRequestServerboundAbilitiesServerboundBlockDigServerboundEntityActionServerboundPlayerInputServerboundPlayerLoadedServerboundPongServerboundRecipeBookServerboundDisplayedRecipeServerboundNameItemServerboundResourcePackReceiveServerboundAdvancementTabServerboundSelectTradeServerboundSetBeaconEffectServerboundHeldItemSlotServerboundUpdateCommandBlockServerboundUpdateCommandBlockMinecartServerboundSetCreativeSlotServerboundUpdateJigsawBlockServerboundUpdateStructureBlockServerboundUpdateSignServerboundArmAnimationServerboundSpectateServerboundBlockPlaceServerboundUseItem"
	_ServerboundPacketID_name_1 = "ServerboundPacketIDGuard"
)

var (
	_ServerboundPacketID_index_0 = [...]uint16{0, 26, 57, 92, 125, 155, 176, 212, 245, 281, 309, 333, 351, 370, 392, 428, 450, 472, 494, 517, 542, 566, 600, 619, 644, 664, 692, 712, 737, 756, 779, 794, 811, 833, 853, 881, 910, 932, 961, 981, 1000, 1023, 1045, 1068, 1083, 1104, 1130, 1149, 1179, 1204, 1226, 1252, 1275, 1304, 1341, 1367, 1395, 1426, 1447, 1470, 1489, 1510, 1528}
)

func (i ServerboundPacketID) String() string {
	switch {
	case 0 <= i && i <= 61:
		return _ServerboundPacketID_name_0[_ServerboundPacketID_index_0[i]:_ServerboundPacketID_index_0[i+1]]
	case i == 2147483647:
		return _ServerboundPacketID_name_1
	default:
		return "ServerboundPacketID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
