//go:build ignore

package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

type slotEntry struct {
	Name string
	ID   int
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	javaFile := filepath.Join(projectRoot, ".mc-decompiled", *version+"-decompiled", "net", "minecraft", "world", "scores", "DisplaySlot.java")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "scoreboard_slot", "slots.go")

	slots, err := parseDisplaySlotJava(javaFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse DisplaySlot.java: %v\n", err)
		os.Exit(1)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/scoreboard_slot; DO NOT EDIT.\n\n")
	buf.WriteString("package scoreboardslot\n\n")

	buf.WriteString(fmt.Sprintf("const ScoreboardSlotCount = %d\n\n", len(slots)))

	buf.WriteString("const (\n")
	for _, s := range slots {
		constName := toConstName(s.Name)
		buf.WriteString(fmt.Sprintf("\tSlot%s int32 = %d\n", constName, s.ID))
	}
	buf.WriteString(")\n\n")

	buf.WriteString("var ScoreboardSlotNames = []string{\n")
	for _, s := range slots {
		buf.WriteString(fmt.Sprintf("\t%q, // %d\n", s.Name, s.ID))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var scoreboardSlotByName = map[string]int32{\n")
	for _, s := range slots {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", s.Name, s.ID))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func ScoreboardSlotIDByName(name string) int32 {
	if id, ok := scoreboardSlotByName[name]; ok {
		return id
	}
	return -1
}

func ScoreboardSlotNameByID(id int32) string {
	if id < 0 || int(id) >= len(ScoreboardSlotNames) {
		return ""
	}
	return ScoreboardSlotNames[id]
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d scoreboard slots)\n", outputFile, len(slots))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func toConstName(name string) string {
	name = strings.ReplaceAll(name, ".", "_")
	parts := strings.Split(name, "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}

func parseDisplaySlotJava(javaFile string) ([]slotEntry, error) {
	content, err := os.ReadFile(javaFile)
	if err != nil {
		return nil, err
	}

	// Match enum values like: LIST(0, "list"), SIDEBAR(1, "sidebar"), etc.
	pattern := regexp.MustCompile(`^\s+(\w+)\((\d+),\s*"([^"]+)"\)[,;]`)
	var slots []slotEntry

	for _, line := range strings.Split(string(content), "\n") {
		if matches := pattern.FindStringSubmatch(line); len(matches) > 3 {
			id, _ := strconv.Atoi(matches[2])
			slots = append(slots, slotEntry{Name: matches[3], ID: id})
		}
	}

	return slots, nil
}
