//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

type itemJSON struct {
	ID            int    `json:"id"`
	Name          string `json:"name"`
	DisplayName   string `json:"displayName"`
	StackSize     int    `json:"stackSize"`
	MaxDurability int    `json:"maxDurability"`
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	inputFile := filepath.Join(projectRoot, ".mcdata", *version, "items.json")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "item", "items.go")

	data, err := os.ReadFile(inputFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read: %v\n", err)
		os.Exit(1)
	}

	var items []itemJSON
	if err := json.Unmarshal(data, &items); err != nil {
		fmt.Fprintf(os.Stderr, "parse: %v\n", err)
		os.Exit(1)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/item; DO NOT EDIT.\n\n")
	buf.WriteString("package item\n\n")

	buf.WriteString("type ItemInfo struct {\n")
	buf.WriteString("\tID            int32\n")
	buf.WriteString("\tName          string\n")
	buf.WriteString("\tStackSize     int32\n")
	buf.WriteString("\tMaxDurability int32\n")
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("const ItemCount = %d\n\n", len(items)))

	buf.WriteString("var Items = [...]ItemInfo{\n")
	for _, it := range items {
		buf.WriteString(fmt.Sprintf("\t{ID: %d, Name: %q, StackSize: %d, MaxDurability: %d},\n",
			it.ID, "minecraft:"+it.Name, it.StackSize, it.MaxDurability))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var ItemByName = map[string]int32{\n")
	for _, it := range items {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", "minecraft:"+it.Name, it.ID))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("func GetItemID(name string) int32 {\n")
	buf.WriteString("\tif id, ok := ItemByName[name]; ok {\n")
	buf.WriteString("\t\treturn id\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn -1\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func GetItemInfo(id int32) *ItemInfo {\n")
	buf.WriteString("\tif id < 0 || int(id) >= len(Items) {\n")
	buf.WriteString("\t\treturn nil\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn &Items[id]\n")
	buf.WriteString("}\n")

	source := buf.String()
	formatted, err := format.Source([]byte(source))
	if err != nil {
		fmt.Fprintf(os.Stderr, "gofmt: %v\n", err)
		formatted = []byte(source)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d items)\n", outputFile, len(items))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}
