//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type recipeJSON struct {
	Type   string `json:"type"`
	Result any    `json:"result"`
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	inputFile := filepath.Join(projectRoot, ".mcdata", *version, "recipes.json")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "recipes", "recipes.go")

	data, err := os.ReadFile(inputFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read recipes.json: %v\n", err)
		os.Exit(1)
	}

	var rawRecipes map[string][]json.RawMessage
	if err := json.Unmarshal(data, &rawRecipes); err != nil {
		fmt.Fprintf(os.Stderr, "parse recipes.json: %v\n", err)
		os.Exit(1)
	}

	totalRecipes := 0
	for _, recipes := range rawRecipes {
		totalRecipes += len(recipes)
	}

	var itemIDs []string
	for id := range rawRecipes {
		itemIDs = append(itemIDs, id)
	}
	sort.Strings(itemIDs)

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/recipes; DO NOT EDIT.\n\n")
	buf.WriteString("package recipes\n\n")

	buf.WriteString(fmt.Sprintf("const RecipeCount = %d\n", totalRecipes))
	buf.WriteString(fmt.Sprintf("const CraftableItemCount = %d\n\n", len(rawRecipes)))

	buf.WriteString("var CraftableItems = []int{\n")
	for _, id := range itemIDs {
		buf.WriteString(fmt.Sprintf("\t%s,\n", id))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var RecipesPerItem = map[int]int{\n")
	for _, id := range itemIDs {
		buf.WriteString(fmt.Sprintf("\t%s: %d,\n", id, len(rawRecipes[id])))
	}
	buf.WriteString("}\n")

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d recipes, %d craftable items)\n", outputFile, totalRecipes, len(rawRecipes))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func toConstName(name string) string {
	parts := strings.Split(name, "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}
