//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type trimMaterialJSON struct {
	AssetName   string `json:"asset_name"`
	Ingredient  string `json:"ingredient"`
	ItemModelIndex float64 `json:"item_model_index"`
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	datapackDir := filepath.Join(projectRoot, ".mcdata", *version, "datapacks", "trim_material")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "trim_material", "trim_materials.go")

	entries, err := os.ReadDir(datapackDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read trim_material dir: %v\n", err)
		os.Exit(1)
	}

	type materialEntry struct {
		Name       string
		AssetName  string
		Ingredient string
	}

	var materials []materialEntry
	for _, entry := range entries {
		if !strings.HasSuffix(entry.Name(), ".json") {
			continue
		}

		data, err := os.ReadFile(filepath.Join(datapackDir, entry.Name()))
		if err != nil {
			continue
		}

		var m trimMaterialJSON
		if err := json.Unmarshal(data, &m); err != nil {
			continue
		}

		name := "minecraft:" + strings.TrimSuffix(entry.Name(), ".json")
		materials = append(materials, materialEntry{
			Name:       name,
			AssetName:  m.AssetName,
			Ingredient: m.Ingredient,
		})
	}

	sort.Slice(materials, func(i, j int) bool {
		return materials[i].Name < materials[j].Name
	})

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/trim_material; DO NOT EDIT.\n\n")
	buf.WriteString("package trimmaterial\n\n")

	buf.WriteString("type TrimMaterialInfo struct {\n")
	buf.WriteString("\tID         int32\n")
	buf.WriteString("\tName       string\n")
	buf.WriteString("\tAssetName  string\n")
	buf.WriteString("\tIngredient string\n")
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("const TrimMaterialCount = %d\n\n", len(materials)))

	buf.WriteString("var TrimMaterials = []TrimMaterialInfo{\n")
	for i, m := range materials {
		buf.WriteString(fmt.Sprintf("\t{ID: %d, Name: %q, AssetName: %q, Ingredient: %q},\n",
			i, m.Name, m.AssetName, m.Ingredient))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var trimMaterialByName = map[string]int32{\n")
	for i, m := range materials {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", m.Name, i))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func TrimMaterialIDByName(name string) int32 {
	if id, ok := trimMaterialByName[name]; ok {
		return id
	}
	return -1
}

func TrimMaterialByID(id int32) *TrimMaterialInfo {
	if id < 0 || int(id) >= len(TrimMaterials) {
		return nil
	}
	return &TrimMaterials[id]
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d trim materials)\n", outputFile, len(materials))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}
