//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type jukeboxSongJSON struct {
	SoundEvent    any     `json:"sound_event"`
	Description   any     `json:"description"`
	LengthInSeconds float64 `json:"length_in_seconds"`
	ComparatorOutput int   `json:"comparator_output"`
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	datapackDir := filepath.Join(projectRoot, ".mcdata", *version, "datapacks", "jukebox_song")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "jukebox_song", "jukebox_songs.go")

	entries, err := os.ReadDir(datapackDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read jukebox_song dir: %v\n", err)
		os.Exit(1)
	}

	type songEntry struct {
		Name             string
		LengthInSeconds  float64
		ComparatorOutput int
	}

	var songs []songEntry
	for _, entry := range entries {
		if !strings.HasSuffix(entry.Name(), ".json") {
			continue
		}

		data, err := os.ReadFile(filepath.Join(datapackDir, entry.Name()))
		if err != nil {
			continue
		}

		var song jukeboxSongJSON
		if err := json.Unmarshal(data, &song); err != nil {
			continue
		}

		name := "minecraft:" + strings.TrimSuffix(entry.Name(), ".json")
		songs = append(songs, songEntry{
			Name:             name,
			LengthInSeconds:  song.LengthInSeconds,
			ComparatorOutput: song.ComparatorOutput,
		})
	}

	sort.Slice(songs, func(i, j int) bool {
		return songs[i].Name < songs[j].Name
	})

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/jukebox_song; DO NOT EDIT.\n\n")
	buf.WriteString("package jukeboxsong\n\n")

	buf.WriteString("type JukeboxSongInfo struct {\n")
	buf.WriteString("\tID               int32\n")
	buf.WriteString("\tName             string\n")
	buf.WriteString("\tLengthInSeconds  float64\n")
	buf.WriteString("\tComparatorOutput int32\n")
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("const JukeboxSongCount = %d\n\n", len(songs)))

	buf.WriteString("var JukeboxSongs = []JukeboxSongInfo{\n")
	for i, s := range songs {
		buf.WriteString(fmt.Sprintf("\t{ID: %d, Name: %q, LengthInSeconds: %v, ComparatorOutput: %d},\n",
			i, s.Name, s.LengthInSeconds, s.ComparatorOutput))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var jukeboxSongByName = map[string]int32{\n")
	for i, s := range songs {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", s.Name, i))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func JukeboxSongIDByName(name string) int32 {
	if id, ok := jukeboxSongByName[name]; ok {
		return id
	}
	return -1
}

func JukeboxSongByID(id int32) *JukeboxSongInfo {
	if id < 0 || int(id) >= len(JukeboxSongs) {
		return nil
	}
	return &JukeboxSongs[id]
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d jukebox songs)\n", outputFile, len(songs))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}
