//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type stateSpec struct {
	name       string
	stateLabel string
}

var states = []stateSpec{
	{name: "login", stateLabel: "Login"},
	{name: "status", stateLabel: "Status"},
	{name: "configuration", stateLabel: "Config"},
	{name: "play", stateLabel: ""},
}

type packetEntry struct {
	hexID int
	name  string
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	root, err := findProjectRoot()
	if err != nil {
		log.Fatalf("find project root: %v", err)
	}

	protoPath := filepath.Join(root, ".mcdata", *version, "protocol.json")
	data, err := os.ReadFile(protoPath)
	if err != nil {
		log.Fatalf("read protocol.json: %v", err)
	}

	var protocol map[string]json.RawMessage
	if err := json.Unmarshal(data, &protocol); err != nil {
		log.Fatalf("parse protocol.json: %v", err)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/packet; DO NOT EDIT.\n\n")
	buf.WriteString("package packet\n\n")
	buf.WriteString("//go:generate stringer -type ClientboundPacketID\n")
	buf.WriteString("//go:generate stringer -type ServerboundPacketID\n\n")
	buf.WriteString("type (\n")
	buf.WriteString("\tClientboundPacketID int32\n")
	buf.WriteString("\tServerboundPacketID int32\n")
	buf.WriteString(")\n")

	for _, s := range states {
		clientbound, err := extractMappings(protocol, s.name, "toClient")
		if err != nil {
			log.Fatalf("extract %s.toClient: %v", s.name, err)
		}
		serverbound, err := extractMappings(protocol, s.name, "toServer")
		if err != nil {
			log.Fatalf("extract %s.toServer: %v", s.name, err)
		}

		writeConstBlock(&buf, clientbound, "Clientbound", s.stateLabel, "ClientboundPacketID")
		writeConstBlock(&buf, serverbound, "Serverbound", s.stateLabel, "ServerboundPacketID")
	}

	buf.WriteString("// ClientboundPacketIDGuard is a sentinel for bounds checking.\n")
	buf.WriteString("const ClientboundPacketIDGuard ClientboundPacketID = 0x7FFFFFFF\n\n")
	buf.WriteString("// ServerboundPacketIDGuard is a sentinel for bounds checking.\n")
	buf.WriteString("const ServerboundPacketIDGuard ServerboundPacketID = 0x7FFFFFFF\n")

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		log.Fatalf("gofmt: %v\n\nRaw output:\n%s", err, buf.String())
	}

	outDir := filepath.Join(root, "internal", "data", "generated", "packet")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		log.Fatalf("mkdir: %v", err)
	}
	outPath := filepath.Join(outDir, "packetid.go")
	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		log.Fatalf("write: %v", err)
	}

	fmt.Printf("Generated %s (%d bytes)\n", outPath, len(formatted))
}

func extractMappings(protocol map[string]json.RawMessage, state, direction string) ([]packetEntry, error) {
	var stateData map[string]json.RawMessage
	if err := json.Unmarshal(protocol[state], &stateData); err != nil {
		return nil, fmt.Errorf("unmarshal state %s: %w", state, err)
	}

	var dirData map[string]json.RawMessage
	if err := json.Unmarshal(stateData[direction], &dirData); err != nil {
		return nil, fmt.Errorf("unmarshal %s.%s: %w", state, direction, err)
	}

	var types map[string]json.RawMessage
	if err := json.Unmarshal(dirData["types"], &types); err != nil {
		return nil, fmt.Errorf("unmarshal types: %w", err)
	}

	var packetType []json.RawMessage
	if err := json.Unmarshal(types["packet"], &packetType); err != nil {
		return nil, fmt.Errorf("unmarshal packet type: %w", err)
	}

	if len(packetType) < 2 {
		return nil, fmt.Errorf("unexpected packet type structure")
	}

	var fields []json.RawMessage
	if err := json.Unmarshal(packetType[1], &fields); err != nil {
		return nil, fmt.Errorf("unmarshal packet fields: %w", err)
	}

	var nameField struct {
		Name string            `json:"name"`
		Type []json.RawMessage `json:"type"`
	}
	if err := json.Unmarshal(fields[0], &nameField); err != nil {
		return nil, fmt.Errorf("unmarshal name field: %w", err)
	}

	var mapper struct {
		Mappings map[string]string `json:"mappings"`
	}
	if err := json.Unmarshal(nameField.Type[1], &mapper); err != nil {
		return nil, fmt.Errorf("unmarshal mapper: %w", err)
	}

	var entries []packetEntry
	for hexStr, name := range mapper.Mappings {
		id, err := strconv.ParseInt(strings.TrimPrefix(hexStr, "0x"), 16, 32)
		if err != nil {
			return nil, fmt.Errorf("parse hex %s: %w", hexStr, err)
		}
		entries = append(entries, packetEntry{hexID: int(id), name: name})
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].hexID < entries[j].hexID
	})

	return entries, nil
}

func writeConstBlock(buf *strings.Builder, entries []packetEntry, dirPrefix, stateLabel, typeName string) {
	if len(entries) == 0 {
		return
	}

	label := dirPrefix
	if stateLabel != "" {
		label += " " + stateLabel
	} else {
		label += " Play"
	}
	buf.WriteString(fmt.Sprintf("\n// %s\n", label))
	buf.WriteString("const (\n")

	for i, e := range entries {
		constName := buildConstName(e.name, dirPrefix, stateLabel)
		if i == 0 {
			buf.WriteString(fmt.Sprintf("\t%s %s = iota\n", constName, typeName))
		} else {
			buf.WriteString(fmt.Sprintf("\t%s\n", constName))
		}
	}

	buf.WriteString(")\n")
}

func buildConstName(snakeName, dirPrefix, stateLabel string) string {
	pascal := snakeToPascal(snakeName)
	if stateLabel != "" {
		return dirPrefix + stateLabel + pascal
	}
	return dirPrefix + pascal
}

func snakeToPascal(s string) string {
	parts := strings.Split(s, "_")
	var result strings.Builder
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		result.WriteString(strings.ToUpper(p[:1]))
		result.WriteString(p[1:])
	}
	return result.String()
}

func findProjectRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found")
		}
		dir = parent
	}
}
