//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type recipeJSON struct {
	Type        string `json:"type"`
	Category    string `json:"category"`
	CookingTime int    `json:"cookingtime"`
	Experience  float64 `json:"experience"`
	Group       string `json:"group"`
	Ingredient  any    `json:"ingredient"`
	Result      struct {
		ID    string `json:"id"`
		Count int    `json:"count"`
	} `json:"result"`
}

type cookingRecipe struct {
	RecipeID    string
	RecipeType  string
	Ingredient  string
	Result      string
	ResultCount int
	CookingTime int
	Experience  float64
	Category    string
	Group       string
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	recipeDir := filepath.Join(projectRoot, ".mcdata", *version, "recipes")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "smelting", "smelting.go")

	recipes, err := parseRecipes(recipeDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse recipes: %v\n", err)
		os.Exit(1)
	}

	sort.Slice(recipes, func(i, j int) bool {
		if recipes[i].RecipeType != recipes[j].RecipeType {
			return recipes[i].RecipeType < recipes[j].RecipeType
		}
		return recipes[i].Ingredient < recipes[j].Ingredient
	})

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/smelting; DO NOT EDIT.\n\n")
	buf.WriteString("package smelting\n\n")

	buf.WriteString("type RecipeType int\n\n")
	buf.WriteString("const (\n")
	buf.WriteString("\tSmelting RecipeType = iota\n")
	buf.WriteString("\tBlasting\n")
	buf.WriteString("\tSmoking\n")
	buf.WriteString("\tCampfireCooking\n")
	buf.WriteString(")\n\n")

	buf.WriteString("type CookingRecipe struct {\n")
	buf.WriteString("\tRecipeID    string\n")
	buf.WriteString("\tType        RecipeType\n")
	buf.WriteString("\tIngredient  string\n")
	buf.WriteString("\tResult      string\n")
	buf.WriteString("\tResultCount int\n")
	buf.WriteString("\tCookingTime int\n")
	buf.WriteString("\tExperience  float64\n")
	buf.WriteString("\tCategory    string\n")
	buf.WriteString("\tGroup       string\n")
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("const CookingRecipeCount = %d\n\n", len(recipes)))

	buf.WriteString("var CookingRecipes = []CookingRecipe{\n")
	for _, r := range recipes {
		typeConst := "Smelting"
		switch r.RecipeType {
		case "minecraft:blasting":
			typeConst = "Blasting"
		case "minecraft:smoking":
			typeConst = "Smoking"
		case "minecraft:campfire_cooking":
			typeConst = "CampfireCooking"
		}
		count := r.ResultCount
		if count == 0 {
			count = 1
		}
		buf.WriteString(fmt.Sprintf("\t{RecipeID: %q, Type: %s, Ingredient: %q, Result: %q, ResultCount: %d, CookingTime: %d, Experience: %.2f, Category: %q, Group: %q},\n",
			r.RecipeID, typeConst, r.Ingredient, r.Result, count, r.CookingTime, r.Experience, r.Category, r.Group))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var recipesByIngredient = make(map[string]map[RecipeType]*CookingRecipe)\n\n")

	buf.WriteString("func init() {\n")
	buf.WriteString("\tfor i := range CookingRecipes {\n")
	buf.WriteString("\t\tr := &CookingRecipes[i]\n")
	buf.WriteString("\t\tif recipesByIngredient[r.Ingredient] == nil {\n")
	buf.WriteString("\t\t\trecipesByIngredient[r.Ingredient] = make(map[RecipeType]*CookingRecipe)\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t\trecipesByIngredient[r.Ingredient][r.Type] = r\n")
	buf.WriteString("\t}\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func GetRecipe(ingredient string, recipeType RecipeType) *CookingRecipe {\n")
	buf.WriteString("\tif m, ok := recipesByIngredient[ingredient]; ok {\n")
	buf.WriteString("\t\treturn m[recipeType]\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn nil\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func GetSmeltingRecipe(ingredient string) *CookingRecipe {\n")
	buf.WriteString("\treturn GetRecipe(ingredient, Smelting)\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func GetBlastingRecipe(ingredient string) *CookingRecipe {\n")
	buf.WriteString("\treturn GetRecipe(ingredient, Blasting)\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func GetSmokingRecipe(ingredient string) *CookingRecipe {\n")
	buf.WriteString("\treturn GetRecipe(ingredient, Smoking)\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func GetCampfireRecipe(ingredient string) *CookingRecipe {\n")
	buf.WriteString("\treturn GetRecipe(ingredient, CampfireCooking)\n")
	buf.WriteString("}\n")

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d cooking recipes)\n", outputFile, len(recipes))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func parseRecipes(recipeDir string) ([]cookingRecipe, error) {
	var recipes []cookingRecipe

	files, err := os.ReadDir(recipeDir)
	if err != nil {
		return nil, err
	}

	for _, f := range files {
		if f.IsDir() || !strings.HasSuffix(f.Name(), ".json") {
			continue
		}

		data, err := os.ReadFile(filepath.Join(recipeDir, f.Name()))
		if err != nil {
			continue
		}

		var r recipeJSON
		if err := json.Unmarshal(data, &r); err != nil {
			continue
		}

		if r.Type != "minecraft:smelting" && r.Type != "minecraft:blasting" &&
			r.Type != "minecraft:smoking" && r.Type != "minecraft:campfire_cooking" {
			continue
		}

		ingredient := extractIngredient(r.Ingredient)
		if ingredient == "" {
			continue
		}

		recipeID := "minecraft:" + strings.TrimSuffix(f.Name(), ".json")

		recipes = append(recipes, cookingRecipe{
			RecipeID:    recipeID,
			RecipeType:  r.Type,
			Ingredient:  ingredient,
			Result:      r.Result.ID,
			ResultCount: r.Result.Count,
			CookingTime: r.CookingTime,
			Experience:  r.Experience,
			Category:    r.Category,
			Group:       r.Group,
		})
	}

	return recipes, nil
}

func extractIngredient(ing any) string {
	switch v := ing.(type) {
	case string:
		return v
	case map[string]any:
		if item, ok := v["item"].(string); ok {
			return item
		}
		if tag, ok := v["tag"].(string); ok {
			return "#" + tag
		}
	case []any:
		if len(v) > 0 {
			return extractIngredient(v[0])
		}
	}
	return ""
}
