//go:build ignore

package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

type ruleEntry struct {
	Name     string
	Type     string
	Category string
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	javaFile := filepath.Join(projectRoot, ".mc-decompiled", *version+"-decompiled", "net", "minecraft", "world", "level", "GameRules.java")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "game_rules", "rules.go")

	rules, err := parseGameRulesJava(javaFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse GameRules.java: %v\n", err)
		os.Exit(1)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/game_rules; DO NOT EDIT.\n\n")
	buf.WriteString("package gamerules\n\n")

	buf.WriteString(fmt.Sprintf("const GameRuleCount = %d\n\n", len(rules)))

	buf.WriteString("type GameRuleInfo struct {\n")
	buf.WriteString("\tName     string\n")
	buf.WriteString("\tType     string\n")
	buf.WriteString("\tCategory string\n")
	buf.WriteString("}\n\n")

	buf.WriteString("var GameRules = []GameRuleInfo{\n")
	for _, r := range rules {
		buf.WriteString(fmt.Sprintf("\t{Name: %q, Type: %q, Category: %q},\n", r.Name, r.Type, r.Category))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var gameRuleByName = map[string]int{\n")
	for i, r := range rules {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", r.Name, i))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func GameRuleIndexByName(name string) int {
	if idx, ok := gameRuleByName[name]; ok {
		return idx
	}
	return -1
}

func GameRuleByName(name string) *GameRuleInfo {
	if idx, ok := gameRuleByName[name]; ok {
		return &GameRules[idx]
	}
	return nil
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d game rules)\n", outputFile, len(rules))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func parseGameRulesJava(javaFile string) ([]ruleEntry, error) {
	content, err := os.ReadFile(javaFile)
	if err != nil {
		return nil, err
	}

	// Match: register("doFireTick", GameRules.Category.UPDATES, GameRules.BooleanValue.create(...))
	// or: register("randomTickSpeed", GameRules.Category.UPDATES, GameRules.IntegerValue.create(...))
	pattern := regexp.MustCompile(`register\(\s*"([^"]+)",\s*GameRules\.Category\.(\w+),\s*GameRules\.(\w+)Value\.create`)
	var rules []ruleEntry

	for _, match := range pattern.FindAllStringSubmatch(string(content), -1) {
		if len(match) > 3 {
			rules = append(rules, ruleEntry{
				Name:     match[1],
				Type:     strings.ToLower(match[3]),
				Category: strings.ToLower(match[2]),
			})
		}
	}

	return rules, nil
}
