//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type enchantmentJSON struct {
	Description       any    `json:"description"`
	SupportedItems    string `json:"supported_items"`
	Weight            int    `json:"weight"`
	MaxLevel          int    `json:"max_level"`
	MinCost           any    `json:"min_cost"`
	MaxCost           any    `json:"max_cost"`
	AnvilCost         int    `json:"anvil_cost"`
	Slots             []string `json:"slots"`
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	datapackDir := filepath.Join(projectRoot, ".mcdata", *version, "datapacks", "enchantment")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "enchantment", "enchantments.go")

	entries, err := os.ReadDir(datapackDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read enchantment dir: %v\n", err)
		os.Exit(1)
	}

	type enchEntry struct {
		Name     string
		Weight   int
		MaxLevel int
	}

	var enchantments []enchEntry
	for _, entry := range entries {
		if !strings.HasSuffix(entry.Name(), ".json") {
			continue
		}

		data, err := os.ReadFile(filepath.Join(datapackDir, entry.Name()))
		if err != nil {
			continue
		}

		var ench enchantmentJSON
		if err := json.Unmarshal(data, &ench); err != nil {
			continue
		}

		name := "minecraft:" + strings.TrimSuffix(entry.Name(), ".json")
		enchantments = append(enchantments, enchEntry{
			Name:     name,
			Weight:   ench.Weight,
			MaxLevel: ench.MaxLevel,
		})
	}

	sort.Slice(enchantments, func(i, j int) bool {
		return enchantments[i].Name < enchantments[j].Name
	})

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/enchantment; DO NOT EDIT.\n\n")
	buf.WriteString("package enchantment\n\n")

	buf.WriteString("type EnchantmentInfo struct {\n")
	buf.WriteString("\tID       int32\n")
	buf.WriteString("\tName     string\n")
	buf.WriteString("\tWeight   int32\n")
	buf.WriteString("\tMaxLevel int32\n")
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("const EnchantmentCount = %d\n\n", len(enchantments)))

	buf.WriteString("var Enchantments = []EnchantmentInfo{\n")
	for i, e := range enchantments {
		buf.WriteString(fmt.Sprintf("\t{ID: %d, Name: %q, Weight: %d, MaxLevel: %d},\n",
			i, e.Name, e.Weight, e.MaxLevel))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var enchantmentByName = map[string]int32{\n")
	for i, e := range enchantments {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", e.Name, i))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func EnchantmentIDByName(name string) int32 {
	if id, ok := enchantmentByName[name]; ok {
		return id
	}
	return -1
}

func EnchantmentByID(id int32) *EnchantmentInfo {
	if id < 0 || int(id) >= len(Enchantments) {
		return nil
	}
	return &Enchantments[id]
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d enchantments)\n", outputFile, len(enchantments))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}
