//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type registriesJSON map[string]registryDef

type registryDef struct {
	ProtocolID int                 `json:"protocol_id"`
	Entries    map[string]entryDef `json:"entries"`
}

type entryDef struct {
	ProtocolID int `json:"protocol_id"`
}

type attributeEntry struct {
	Name string
	ID   int
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	inputFile := filepath.Join(projectRoot, ".mcdata", *version, "registries.json")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "attribute", "attributes.go")

	data, err := os.ReadFile(inputFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read registries.json: %v\n", err)
		os.Exit(1)
	}

	var registries registriesJSON
	if err := json.Unmarshal(data, &registries); err != nil {
		fmt.Fprintf(os.Stderr, "parse registries.json: %v\n", err)
		os.Exit(1)
	}

	attrRegistry, ok := registries["minecraft:attribute"]
	if !ok {
		fmt.Fprintf(os.Stderr, "minecraft:attribute registry not found\n")
		os.Exit(1)
	}

	var attributes []attributeEntry
	for name, entry := range attrRegistry.Entries {
		attributes = append(attributes, attributeEntry{Name: name, ID: entry.ProtocolID})
	}
	sort.Slice(attributes, func(i, j int) bool {
		return attributes[i].ID < attributes[j].ID
	})

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/attribute; DO NOT EDIT.\n\n")
	buf.WriteString("package attribute\n\n")

	buf.WriteString("type AttributeInfo struct {\n")
	buf.WriteString("\tID   int32\n")
	buf.WriteString("\tName string\n")
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("const AttributeCount = %d\n\n", len(attributes)))

	buf.WriteString("const (\n")
	for _, attr := range attributes {
		constName := toConstName(strings.TrimPrefix(attr.Name, "minecraft:"))
		buf.WriteString(fmt.Sprintf("\tAttr%s int32 = %d\n", constName, attr.ID))
	}
	buf.WriteString(")\n\n")

	buf.WriteString("var Attributes = []AttributeInfo{\n")
	for _, attr := range attributes {
		buf.WriteString(fmt.Sprintf("\t{ID: %d, Name: %q},\n", attr.ID, attr.Name))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var attributeByName = map[string]int32{\n")
	for _, attr := range attributes {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", attr.Name, attr.ID))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func AttributeIDByName(name string) int32 {
	if id, ok := attributeByName[name]; ok {
		return id
	}
	return -1
}

func AttributeByID(id int32) *AttributeInfo {
	if id < 0 || int(id) >= len(Attributes) {
		return nil
	}
	return &Attributes[id]
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d attributes)\n", outputFile, len(attributes))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func toConstName(name string) string {
	name = strings.TrimPrefix(name, "minecraft:")
	name = strings.ReplaceAll(name, ".", "_")
	parts := strings.Split(name, "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}
