//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

type effectJSON struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	DisplayName string `json:"displayName"`
	Type        string `json:"type"`
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	inputFile := filepath.Join(projectRoot, ".mcdata", *version, "effects.json")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "effect", "effects.go")

	data, err := os.ReadFile(inputFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read effects.json: %v\n", err)
		os.Exit(1)
	}

	var effects []effectJSON
	if err := json.Unmarshal(data, &effects); err != nil {
		fmt.Fprintf(os.Stderr, "parse effects.json: %v\n", err)
		os.Exit(1)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/effect; DO NOT EDIT.\n\n")
	buf.WriteString("package effect\n\n")

	buf.WriteString("type EffectInfo struct {\n")
	buf.WriteString("\tID   int32\n")
	buf.WriteString("\tName string\n")
	buf.WriteString("\tType string\n")
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("const EffectCount = %d\n\n", len(effects)))

	buf.WriteString("const (\n")
	for _, e := range effects {
		constName := toConstName(e.Name)
		buf.WriteString(fmt.Sprintf("\tEffect%s int32 = %d\n", constName, e.ID))
	}
	buf.WriteString(")\n\n")

	buf.WriteString("var Effects = []EffectInfo{\n")
	for _, e := range effects {
		buf.WriteString(fmt.Sprintf("\t{ID: %d, Name: %q, Type: %q},\n", e.ID, e.Name, e.Type))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var effectByName = map[string]*EffectInfo{\n")
	for i, e := range effects {
		buf.WriteString(fmt.Sprintf("\t%q: &Effects[%d],\n", e.Name, i))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var effectByID = map[int32]*EffectInfo{\n")
	for i, e := range effects {
		buf.WriteString(fmt.Sprintf("\t%d: &Effects[%d],\n", e.ID, i))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func EffectByName(name string) *EffectInfo {
	return effectByName[name]
}

func EffectByID(id int32) *EffectInfo {
	return effectByID[id]
}

func EffectIDByName(name string) int32 {
	if e := effectByName[name]; e != nil {
		return e.ID
	}
	return -1
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d effects)\n", outputFile, len(effects))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func toConstName(name string) string {
	parts := strings.Split(name, "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}
