//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	structuresDir := filepath.Join(projectRoot, ".mcdata", *version, "datapacks", "worldgen", "structure")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "structures", "structures.go")

	structures, err := parseStructures(structuresDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse structures: %v\n", err)
		os.Exit(1)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/structures; DO NOT EDIT.\n\n")
	buf.WriteString("package structures\n\n")

	buf.WriteString(fmt.Sprintf("const StructureCount = %d\n\n", len(structures)))

	buf.WriteString("var StructureNames = []string{\n")
	for _, s := range structures {
		buf.WriteString(fmt.Sprintf("\t%q,\n", s))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var structureByName = map[string]int{\n")
	for i, s := range structures {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", s, i))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func StructureIndexByName(name string) int {
	if idx, ok := structureByName[name]; ok {
		return idx
	}
	return -1
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d structures)\n", outputFile, len(structures))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func parseStructures(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	var structures []string
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".json") {
			continue
		}
		name := strings.TrimSuffix(e.Name(), ".json")
		
		// Read JSON to get the structure type
		data, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			continue
		}
		var structData struct {
			Type string `json:"type"`
		}
		if err := json.Unmarshal(data, &structData); err == nil {
			structures = append(structures, "minecraft:"+name)
		}
	}

	sort.Strings(structures)
	return structures, nil
}
