//go:build ignore

package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

type worldEventEntry struct {
	Name string
	ID   int
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	javaFile := filepath.Join(projectRoot, ".mc-decompiled", *version+"-decompiled", "net", "minecraft", "world", "level", "block", "LevelEvent.java")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "world_event", "world_events.go")

	worldEvents, err := parseLevelEventJava(javaFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse LevelEvent.java: %v\n", err)
		os.Exit(1)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/world_event; DO NOT EDIT.\n\n")
	buf.WriteString("package worldevent\n\n")

	buf.WriteString(fmt.Sprintf("const WorldEventCount = %d\n\n", len(worldEvents)))

	buf.WriteString("const (\n")
	for _, e := range worldEvents {
		constName := toConstName(e.Name)
		buf.WriteString(fmt.Sprintf("\tEvent%s int32 = %d\n", constName, e.ID))
	}
	buf.WriteString(")\n\n")

	buf.WriteString("var worldEventByID = map[int32]string{\n")
	for _, e := range worldEvents {
		buf.WriteString(fmt.Sprintf("\t%d: %q,\n", e.ID, e.Name))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func WorldEventNameByID(id int32) string {
	return worldEventByID[id]
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d world events)\n", outputFile, len(worldEvents))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func toConstName(name string) string {
	parts := strings.Split(name, "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}

func parseLevelEventJava(javaFile string) ([]worldEventEntry, error) {
	content, err := os.ReadFile(javaFile)
	if err != nil {
		return nil, err
	}

	// Match: public static final int SOUND_DISPENSER_DISPENSE = 1000;
	pattern := regexp.MustCompile(`public static final int (\w+) = (\d+);`)
	var events []worldEventEntry

	for _, line := range strings.Split(string(content), "\n") {
		if matches := pattern.FindStringSubmatch(line); len(matches) > 2 {
			id, _ := strconv.Atoi(matches[2])
			name := camelToSnake(matches[1])
			events = append(events, worldEventEntry{Name: name, ID: id})
		}
	}

	return events, nil
}

func camelToSnake(s string) string {
	var result strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			result.WriteRune('_')
		}
		result.WriteRune(r)
	}
	return strings.ToLower(result.String())
}
