//go:build ignore

package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

type poseEntry struct {
	Name string
	ID   int
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	javaFile := filepath.Join(projectRoot, ".mc-decompiled", *version+"-decompiled", "net", "minecraft", "world", "entity", "Pose.java")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "entity_pose", "poses.go")

	poses, err := parsePoseJava(javaFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse Pose.java: %v\n", err)
		os.Exit(1)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/entity_pose; DO NOT EDIT.\n\n")
	buf.WriteString("package entitypose\n\n")

	buf.WriteString(fmt.Sprintf("const PoseCount = %d\n\n", len(poses)))

	buf.WriteString("const (\n")
	for i, pose := range poses {
		constName := toConstName(pose)
		buf.WriteString(fmt.Sprintf("\tPose%s int32 = %d\n", constName, i))
	}
	buf.WriteString(")\n\n")

	buf.WriteString("var PoseNames = []string{\n")
	for _, pose := range poses {
		buf.WriteString(fmt.Sprintf("\t%q,\n", pose))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var poseByName = map[string]int32{\n")
	for i, pose := range poses {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", pose, i))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func PoseIDByName(name string) int32 {
	if id, ok := poseByName[name]; ok {
		return id
	}
	return -1
}

func PoseNameByID(id int32) string {
	if id < 0 || int(id) >= len(PoseNames) {
		return ""
	}
	return PoseNames[id]
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d poses)\n", outputFile, len(poses))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func toConstName(name string) string {
	parts := strings.Split(name, "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}

func parsePoseJava(javaFile string) ([]string, error) {
	content, err := os.ReadFile(javaFile)
	if err != nil {
		return nil, err
	}

	// Match enum values like: STANDING(0), FALL_FLYING(1), etc.
	pattern := regexp.MustCompile(`^\s+(\w+)\((\d+)\)[,;]`)
	var poses []string

	for _, line := range strings.Split(string(content), "\n") {
		if matches := pattern.FindStringSubmatch(line); len(matches) > 1 {
			poses = append(poses, strings.ToLower(matches[1]))
		}
	}

	return poses, nil
}
