//go:build ignore

// Command generator produces Go source files for the Vitis registry system.
//
// It reads:
//   - .mcdata/<version>/registries.json for all 78 registry ID tables
//   - .mcdata/<version>/datapacks/ for configuration registry NBT data
//
// It outputs:
//   - internal/data/generated/registry/ids.go       — all 78 registries as []string slices
//   - internal/data/generated/registry/config_nbt.go — pre-encoded NBT bytes for config registries
//
// Note: Tags are generated separately by internal/data/generator/tags.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"github.com/vitismc/vitis/internal/nbt"
)

// registriesJSON mirrors the structure of registries.json generated by the vanilla server.
type registriesJSON map[string]registryDef

type registryDef struct {
	ProtocolID int                 `json:"protocol_id"`
	Entries    map[string]entryDef `json:"entries"`
}

type entryDef struct {
	ProtocolID int `json:"protocol_id"`
}

// configRegistries lists the synchronized registries that need HasData=true NBT.
// Maps registry key → data pack subdirectory under .mcdata/<version>/datapacks/
var configRegistries = map[string]string{
	"minecraft:banner_pattern":   "banner_pattern",
	"minecraft:chat_type":        "chat_type",
	"minecraft:damage_type":      "damage_type",
	"minecraft:dimension_type":   "dimension_type",
	"minecraft:enchantment":      "enchantment",
	"minecraft:instrument":       "instrument",
	"minecraft:jukebox_song":     "jukebox_song",
	"minecraft:painting_variant": "painting_variant",
	"minecraft:trim_material":    "trim_material",
	"minecraft:trim_pattern":     "trim_pattern",
	"minecraft:wolf_variant":     "wolf_variant",
	"minecraft:worldgen/biome":   "worldgen/biome",
}

// doubleFields contains field names that must be encoded as NBT Double
// instead of the default Float for decimal numbers.
// Key format: "field_name" — applies in any context.
var doubleFields = map[string]bool{
	"coordinate_scale": true,
	"offset":           true, // biome mood_sound offset
}

// longFields contains field names that must be encoded as NBT Long
// instead of the default Int for integer numbers.
var longFields = map[string]bool{
	"fixed_time": true,
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	rootDir := findProjectRoot()

	registriesPath := filepath.Join(rootDir, ".mcdata", *version, "registries.json")
	datapacksDir := filepath.Join(rootDir, ".mcdata", *version, "datapacks")
	outDir := filepath.Join(rootDir, "internal", "data", "generated", "registry")

	os.MkdirAll(outDir, 0o755)

	regs := loadRegistries(registriesPath)

	generateIDs(regs, outDir)
	generateConfigNBT(regs, datapacksDir, outDir)

	log.Println("Code generation complete.")
}

func findProjectRoot() string {
	dir, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			log.Fatal("could not find project root (no go.mod)")
		}
		dir = parent
	}
}

func loadRegistries(path string) registriesJSON {
	data, err := os.ReadFile(path)
	if err != nil {
		log.Fatalf("read registries.json: %v", err)
	}
	var regs registriesJSON
	if err := json.Unmarshal(data, &regs); err != nil {
		log.Fatalf("parse registries.json: %v", err)
	}
	return regs
}

// generateIDs produces ids.go with all 78 registries as ordered []string slices.
func generateIDs(regs registriesJSON, outDir string) {
	var b strings.Builder
	b.WriteString("// Code generated by internal/data/generator/registry. DO NOT EDIT.\n\n")
	b.WriteString("package registry\n\n")

	names := make([]string, 0, len(regs))
	for name := range regs {
		names = append(names, name)
	}
	sort.Strings(names)

	b.WriteString("// AllRegistryNames lists every registry key.\n")
	b.WriteString("var AllRegistryNames = []string{\n")
	for _, name := range names {
		fmt.Fprintf(&b, "\t%q,\n", name)
	}
	b.WriteString("}\n\n")

	for _, regName := range names {
		reg := regs[regName]
		varName := registryVarName(regName)

		type idEntry struct {
			Name string
			ID   int
		}
		entries := make([]idEntry, 0, len(reg.Entries))
		for eName, eDef := range reg.Entries {
			entries = append(entries, idEntry{Name: eName, ID: eDef.ProtocolID})
		}
		sort.Slice(entries, func(i, j int) bool {
			return entries[i].ID < entries[j].ID
		})

		fmt.Fprintf(&b, "// %s contains %d entries for %s.\n", varName, len(entries), regName)
		fmt.Fprintf(&b, "var %s = []string{\n", varName)
		for _, e := range entries {
			fmt.Fprintf(&b, "\t%q, // %d\n", e.Name, e.ID)
		}
		b.WriteString("}\n\n")
	}

	writeGoFile(filepath.Join(outDir, "ids.go"), b.String())
	log.Printf("Generated ids.go with %d registries", len(names))
}

// generateConfigNBT produces config_nbt.go with pre-encoded NBT byte slices
// for all configuration registry entries.
func generateConfigNBT(regs registriesJSON, datapacksDir string, outDir string) {
	var b strings.Builder
	b.WriteString("// Code generated by internal/data/generator/registry. DO NOT EDIT.\n\n")
	b.WriteString("package registry\n\n")

	b.WriteString("// ConfigRegistryNames lists the synchronized configuration registry keys in send order.\n")
	b.WriteString("var ConfigRegistryNames = []string{\n")

	orderedConfigs := make([]string, 0, len(configRegistries))
	for k := range configRegistries {
		orderedConfigs = append(orderedConfigs, k)
	}
	sort.Strings(orderedConfigs)

	for _, name := range orderedConfigs {
		fmt.Fprintf(&b, "\t%q,\n", name)
	}
	b.WriteString("}\n\n")

	b.WriteString("// ConfigNBTEntry holds a registry entry name and its pre-encoded NBT bytes.\n")
	b.WriteString("type ConfigNBTEntry struct {\n")
	b.WriteString("\tName string\n")
	b.WriteString("\tData []byte\n")
	b.WriteString("}\n\n")

	b.WriteString("// ConfigRegistryData returns all configuration registry entries with pre-encoded NBT.\n")
	b.WriteString("func ConfigRegistryData() map[string][]ConfigNBTEntry {\n")
	b.WriteString("\treturn map[string][]ConfigNBTEntry{\n")

	totalEntries := 0

	for _, regName := range orderedConfigs {
		subdir := configRegistries[regName]
		dirPath := filepath.Join(datapacksDir, subdir)

		entryNames := resolveConfigEntryOrder(regs, regName, dirPath)

		fmt.Fprintf(&b, "\t\t%q: {\n", regName)

		for _, entryName := range entryNames {
			shortName := strings.TrimPrefix(entryName, "minecraft:")
			jsonPath := filepath.Join(dirPath, shortName+".json")

			jsonData, err := os.ReadFile(jsonPath)
			if err != nil {
				log.Fatalf("read %s: %v", jsonPath, err)
			}

			nbtBytes, err := jsonToNBT(jsonData)
			if err != nil {
				log.Fatalf("convert %s to NBT: %v", jsonPath, err)
			}

			fmt.Fprintf(&b, "\t\t\t{Name: %q, Data: []byte{", entryName)
			for i, bv := range nbtBytes {
				if i > 0 {
					b.WriteString(", ")
				}
				fmt.Fprintf(&b, "0x%02x", bv)
			}
			b.WriteString("}},\n")
			totalEntries++
		}

		b.WriteString("\t\t},\n")
	}

	b.WriteString("\t}\n")
	b.WriteString("}\n")

	writeGoFile(filepath.Join(outDir, "config_nbt.go"), b.String())
	log.Printf("Generated config_nbt.go with %d registries, %d total entries", len(configRegistries), totalEntries)
}

// resolveConfigEntryOrder returns the ordered list of namespaced entry names
// for a configuration registry. If the registry exists in registries.json,
// entries are ordered by protocol_id. Otherwise, entries are derived from
// the data pack directory and sorted alphabetically (vanilla behavior for
// data-driven registries).
func resolveConfigEntryOrder(regs registriesJSON, regName string, dirPath string) []string {
	if reg, ok := regs[regName]; ok {
		type idEntry struct {
			Name string
			ID   int
		}
		entries := make([]idEntry, 0, len(reg.Entries))
		for eName, eDef := range reg.Entries {
			entries = append(entries, idEntry{Name: eName, ID: eDef.ProtocolID})
		}
		sort.Slice(entries, func(i, j int) bool {
			return entries[i].ID < entries[j].ID
		})
		names := make([]string, len(entries))
		for i, e := range entries {
			names[i] = e.Name
		}
		return names
	}

	files, err := os.ReadDir(dirPath)
	if err != nil {
		log.Fatalf("read datapack dir %s: %v", dirPath, err)
	}
	var names []string
	for _, f := range files {
		if f.IsDir() || !strings.HasSuffix(f.Name(), ".json") {
			continue
		}
		baseName := strings.TrimSuffix(f.Name(), ".json")
		names = append(names, "minecraft:"+baseName)
	}
	sort.Strings(names)
	return names
}

// jsonToNBT converts a JSON data pack entry to pre-encoded network NBT bytes.
func jsonToNBT(data []byte) ([]byte, error) {
	var raw interface{}
	dec := json.NewDecoder(strings.NewReader(string(data)))
	dec.UseNumber()
	if err := dec.Decode(&raw); err != nil {
		return nil, fmt.Errorf("parse JSON: %w", err)
	}

	compound, err := jsonValueToCompound(raw)
	if err != nil {
		return nil, err
	}

	enc := nbt.NewEncoder(256)
	if err := enc.WriteRootCompound(compound); err != nil {
		return nil, fmt.Errorf("encode NBT: %w", err)
	}
	return enc.Bytes(), nil
}

func jsonValueToCompound(v interface{}) (*nbt.Compound, error) {
	m, ok := v.(map[string]interface{})
	if !ok {
		return nil, fmt.Errorf("expected JSON object, got %T", v)
	}

	c := nbt.NewCompound()

	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, key := range keys {
		val := m[key]
		if err := addJSONValue(c, key, val); err != nil {
			return nil, fmt.Errorf("field %q: %w", key, err)
		}
	}
	return c, nil
}

func addJSONValue(c *nbt.Compound, name string, v interface{}) error {
	switch val := v.(type) {
	case bool:
		c.PutBool(name, val)

	case string:
		c.PutString(name, val)

	case json.Number:
		return addJSONNumber(c, name, val)

	case map[string]interface{}:
		sub, err := jsonValueToCompound(v)
		if err != nil {
			return err
		}
		c.PutCompound(name, sub)

	case []interface{}:
		list, err := jsonArrayToList(val)
		if err != nil {
			return fmt.Errorf("array: %w", err)
		}
		c.PutList(name, list)

	case nil:
		// skip null values

	default:
		return fmt.Errorf("unsupported JSON type %T", v)
	}
	return nil
}

func addJSONNumber(c *nbt.Compound, name string, num json.Number) error {
	s := num.String()

	if longFields[name] {
		n, err := num.Int64()
		if err != nil {
			return fmt.Errorf("parse long %q: %w", s, err)
		}
		c.PutLong(name, n)
		return nil
	}

	if doubleFields[name] {
		n, err := num.Float64()
		if err != nil {
			return fmt.Errorf("parse double %q: %w", s, err)
		}
		c.PutDouble(name, n)
		return nil
	}

	if strings.Contains(s, ".") || strings.Contains(s, "e") || strings.Contains(s, "E") {
		n, err := num.Float64()
		if err != nil {
			return fmt.Errorf("parse float %q: %w", s, err)
		}
		c.PutFloat(name, float32(n))
		return nil
	}

	n, err := num.Int64()
	if err != nil {
		return fmt.Errorf("parse int %q: %w", s, err)
	}
	c.PutInt(name, int32(n))
	return nil
}

func jsonArrayToList(arr []interface{}) (*nbt.List, error) {
	if len(arr) == 0 {
		return nbt.NewList(nbt.TagEnd), nil
	}

	elemType := inferNBTListType(arr[0])
	list := nbt.NewList(elemType)

	for _, elem := range arr {
		switch elemType {
		case nbt.TagString:
			s, ok := elem.(string)
			if !ok {
				return nil, fmt.Errorf("expected string in list, got %T", elem)
			}
			list.Add(s)

		case nbt.TagCompound:
			sub, err := jsonValueToCompound(elem)
			if err != nil {
				return nil, err
			}
			list.Add(sub)

		case nbt.TagList:
			subArr, ok := elem.([]interface{})
			if !ok {
				return nil, fmt.Errorf("expected array in list, got %T", elem)
			}
			subList, err := jsonArrayToList(subArr)
			if err != nil {
				return nil, err
			}
			list.Add(subList)

		case nbt.TagInt:
			num, ok := elem.(json.Number)
			if !ok {
				return nil, fmt.Errorf("expected number in list, got %T", elem)
			}
			n, err := num.Int64()
			if err != nil {
				return nil, fmt.Errorf("parse int in list: %w", err)
			}
			list.Add(int32(n))

		case nbt.TagFloat:
			num, ok := elem.(json.Number)
			if !ok {
				return nil, fmt.Errorf("expected number in list, got %T", elem)
			}
			n, err := num.Float64()
			if err != nil {
				return nil, fmt.Errorf("parse float in list: %w", err)
			}
			list.Add(float32(n))

		default:
			return nil, fmt.Errorf("unsupported list element type %d", elemType)
		}
	}
	return list, nil
}

func inferNBTListType(first interface{}) byte {
	switch v := first.(type) {
	case string:
		return nbt.TagString
	case map[string]interface{}:
		return nbt.TagCompound
	case []interface{}:
		return nbt.TagList
	case json.Number:
		s := v.String()
		if strings.Contains(s, ".") || strings.Contains(s, "e") || strings.Contains(s, "E") {
			return nbt.TagFloat
		}
		return nbt.TagInt
	case bool:
		_ = v
		return nbt.TagByte
	default:
		return nbt.TagEnd
	}
}

// registryVarName converts "minecraft:block" → "Block",
// "minecraft:worldgen/biome" → "WorldgenBiome", etc.
func registryVarName(regName string) string {
	name := strings.TrimPrefix(regName, "minecraft:")
	parts := strings.FieldsFunc(name, func(r rune) bool {
		return r == '_' || r == '/' || r == ':'
	})
	var result strings.Builder
	for _, p := range parts {
		if len(p) > 0 {
			runes := []rune(p)
			runes[0] = unicode.ToUpper(runes[0])
			result.WriteString(string(runes))
		}
	}
	return result.String()
}

func writeGoFile(path string, content string) {
	formatted, err := format.Source([]byte(content))
	if err != nil {
		log.Printf("WARNING: gofmt failed for %s: %v (writing unformatted)", path, err)
		formatted = []byte(content)
	}
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		log.Fatalf("write %s: %v", path, err)
	}
}
