//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	languageFile := filepath.Join(projectRoot, ".mcdata", *version, "language.json")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "translation", "translations.go")

	translations, err := parseLanguageJSON(languageFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse language.json: %v\n", err)
		os.Exit(1)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/translation; DO NOT EDIT.\n\n")
	buf.WriteString("package translation\n\n")

	buf.WriteString(fmt.Sprintf("const TranslationCount = %d\n\n", len(translations)))

	buf.WriteString("var Translations = map[string]string{\n")
	keys := make([]string, 0, len(translations))
	for k := range translations {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		buf.WriteString(fmt.Sprintf("\t%q: %q,\n", k, translations[k]))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func Translate(key string) string {
	if val, ok := Translations[key]; ok {
		return val
	}
	return key
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d translations)\n", outputFile, len(translations))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func parseLanguageJSON(path string) (map[string]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var translations map[string]string
	if err := json.Unmarshal(data, &translations); err != nil {
		return nil, err
	}

	return translations, nil
}
