//go:build ignore

package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	javaFile := filepath.Join(projectRoot, ".mc-decompiled", *version+"-decompiled", "net", "minecraft", "world", "effect", "MobEffects.java")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "status_effect", "effects.go")

	effects, err := parseMobEffectsJava(javaFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse MobEffects.java: %v\n", err)
		os.Exit(1)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/status_effect; DO NOT EDIT.\n\n")
	buf.WriteString("package statuseffect\n\n")

	buf.WriteString(fmt.Sprintf("const StatusEffectCount = %d\n\n", len(effects)))

	buf.WriteString("var StatusEffects = []string{\n")
	for _, e := range effects {
		buf.WriteString(fmt.Sprintf("\t%q,\n", e))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var statusEffectByName = map[string]int{\n")
	for i, e := range effects {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", e, i))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func StatusEffectIndexByName(name string) int {
	if idx, ok := statusEffectByName[name]; ok {
		return idx
	}
	return -1
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d status effects)\n", outputFile, len(effects))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func parseMobEffectsJava(javaFile string) ([]string, error) {
	content, err := os.ReadFile(javaFile)
	if err != nil {
		return nil, err
	}

	// Match: public static final Holder<MobEffect> SPEED = register("speed", ...
	pattern := regexp.MustCompile(`public static final Holder<MobEffect> (\w+) = register\("([^"]+)"`)
	var effects []string

	for _, match := range pattern.FindAllStringSubmatch(string(content), -1) {
		if len(match) > 2 {
			effects = append(effects, "minecraft:"+match[2])
		}
	}

	return effects, nil
}
