//go:build ignore

package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

type statusEntry struct {
	Name string
	ID   int
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	javaFile := filepath.Join(projectRoot, ".mc-decompiled", *version+"-decompiled", "net", "minecraft", "world", "entity", "EntityEvent.java")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "entity_status", "statuses.go")

	statuses, err := parseEntityEventJava(javaFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse EntityEvent.java: %v\n", err)
		os.Exit(1)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/entity_status; DO NOT EDIT.\n\n")
	buf.WriteString("package entitystatus\n\n")

	buf.WriteString(fmt.Sprintf("const EntityStatusCount = %d\n\n", len(statuses)))

	buf.WriteString("const (\n")
	for _, s := range statuses {
		constName := toConstName(s.Name)
		buf.WriteString(fmt.Sprintf("\tStatus%s byte = %d\n", constName, s.ID))
	}
	buf.WriteString(")\n\n")

	buf.WriteString("var entityStatusByID = map[byte]string{\n")
	for _, s := range statuses {
		buf.WriteString(fmt.Sprintf("\t%d: %q,\n", s.ID, s.Name))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func EntityStatusNameByID(id byte) string {
	return entityStatusByID[id]
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d entity statuses)\n", outputFile, len(statuses))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func toConstName(name string) string {
	parts := strings.Split(strings.ToLower(name), "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}

func parseEntityEventJava(javaFile string) ([]statusEntry, error) {
	content, err := os.ReadFile(javaFile)
	if err != nil {
		return nil, err
	}

	// Match: public static final byte NAME = 123;
	pattern := regexp.MustCompile(`public static final byte (\w+) = (\d+);`)
	var statuses []statusEntry

	for _, line := range strings.Split(string(content), "\n") {
		if matches := pattern.FindStringSubmatch(line); len(matches) > 2 {
			id, _ := strconv.Atoi(matches[2])
			statuses = append(statuses, statusEntry{Name: matches[1], ID: id})
		}
	}

	return statuses, nil
}
