//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type registriesJSON map[string]registryDef

type registryDef struct {
	ProtocolID int                 `json:"protocol_id"`
	Entries    map[string]entryDef `json:"entries"`
}

type entryDef struct {
	ProtocolID int `json:"protocol_id"`
}

type gameEventEntry struct {
	Name string
	ID   int
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	inputFile := filepath.Join(projectRoot, ".mcdata", *version, "registries.json")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "game_event", "game_events.go")

	data, err := os.ReadFile(inputFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read registries.json: %v\n", err)
		os.Exit(1)
	}

	var registries registriesJSON
	if err := json.Unmarshal(data, &registries); err != nil {
		fmt.Fprintf(os.Stderr, "parse registries.json: %v\n", err)
		os.Exit(1)
	}

	registry, ok := registries["minecraft:game_event"]
	if !ok {
		fmt.Fprintf(os.Stderr, "minecraft:game_event registry not found\n")
		os.Exit(1)
	}

	var events []gameEventEntry
	for name, entry := range registry.Entries {
		events = append(events, gameEventEntry{Name: name, ID: entry.ProtocolID})
	}
	sort.Slice(events, func(i, j int) bool {
		return events[i].ID < events[j].ID
	})

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/game_event; DO NOT EDIT.\n\n")
	buf.WriteString("package gameevent\n\n")

	buf.WriteString(fmt.Sprintf("const GameEventCount = %d\n\n", len(events)))

	buf.WriteString("const (\n")
	for _, e := range events {
		constName := toConstName(strings.TrimPrefix(e.Name, "minecraft:"))
		buf.WriteString(fmt.Sprintf("\tEvent%s int32 = %d\n", constName, e.ID))
	}
	buf.WriteString(")\n\n")

	buf.WriteString("var GameEventNames = []string{\n")
	for _, e := range events {
		buf.WriteString(fmt.Sprintf("\t%q, // %d\n", e.Name, e.ID))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var gameEventByName = map[string]int32{\n")
	for _, e := range events {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", e.Name, e.ID))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func GameEventIDByName(name string) int32 {
	if id, ok := gameEventByName[name]; ok {
		return id
	}
	return -1
}

func GameEventNameByID(id int32) string {
	if id < 0 || int(id) >= len(GameEventNames) {
		return ""
	}
	return GameEventNames[id]
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d game events)\n", outputFile, len(events))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func toConstName(name string) string {
	parts := strings.Split(name, "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}
