//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type bannerPatternJSON struct {
	AssetID        string `json:"asset_id"`
	TranslationKey string `json:"translation_key"`
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	datapackDir := filepath.Join(projectRoot, ".mcdata", *version, "datapacks", "banner_pattern")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "banner_pattern", "banner_patterns.go")

	entries, err := os.ReadDir(datapackDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read banner_pattern dir: %v\n", err)
		os.Exit(1)
	}

	type patternEntry struct {
		Name           string
		AssetID        string
		TranslationKey string
	}

	var patterns []patternEntry
	for _, entry := range entries {
		if !strings.HasSuffix(entry.Name(), ".json") {
			continue
		}

		data, err := os.ReadFile(filepath.Join(datapackDir, entry.Name()))
		if err != nil {
			continue
		}

		var p bannerPatternJSON
		if err := json.Unmarshal(data, &p); err != nil {
			continue
		}

		name := "minecraft:" + strings.TrimSuffix(entry.Name(), ".json")
		patterns = append(patterns, patternEntry{
			Name:           name,
			AssetID:        p.AssetID,
			TranslationKey: p.TranslationKey,
		})
	}

	sort.Slice(patterns, func(i, j int) bool {
		return patterns[i].Name < patterns[j].Name
	})

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/banner_pattern; DO NOT EDIT.\n\n")
	buf.WriteString("package bannerpattern\n\n")

	buf.WriteString("type BannerPatternInfo struct {\n")
	buf.WriteString("\tID             int32\n")
	buf.WriteString("\tName           string\n")
	buf.WriteString("\tAssetID        string\n")
	buf.WriteString("\tTranslationKey string\n")
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("const BannerPatternCount = %d\n\n", len(patterns)))

	buf.WriteString("var BannerPatterns = []BannerPatternInfo{\n")
	for i, p := range patterns {
		buf.WriteString(fmt.Sprintf("\t{ID: %d, Name: %q, AssetID: %q, TranslationKey: %q},\n",
			i, p.Name, p.AssetID, p.TranslationKey))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var bannerPatternByName = map[string]int32{\n")
	for i, p := range patterns {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", p.Name, i))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func BannerPatternIDByName(name string) int32 {
	if id, ok := bannerPatternByName[name]; ok {
		return id
	}
	return -1
}

func BannerPatternByID(id int32) *BannerPatternInfo {
	if id < 0 || int(id) >= len(BannerPatterns) {
		return nil
	}
	return &BannerPatterns[id]
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d banner patterns)\n", outputFile, len(patterns))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}
