//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type itemJSON struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	inputFile := filepath.Join(projectRoot, ".mcdata", *version, "items.json")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "spawn_egg", "spawn_eggs.go")

	data, err := os.ReadFile(inputFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read items.json: %v\n", err)
		os.Exit(1)
	}

	var items []itemJSON
	if err := json.Unmarshal(data, &items); err != nil {
		fmt.Fprintf(os.Stderr, "parse items.json: %v\n", err)
		os.Exit(1)
	}

	type spawnEggEntry struct {
		ItemID     int
		ItemName   string
		EntityName string
	}

	var spawnEggs []spawnEggEntry
	for _, item := range items {
		if strings.HasSuffix(item.Name, "_spawn_egg") {
			entityName := strings.TrimSuffix(item.Name, "_spawn_egg")
			spawnEggs = append(spawnEggs, spawnEggEntry{
				ItemID:     item.ID,
				ItemName:   "minecraft:" + item.Name,
				EntityName: "minecraft:" + entityName,
			})
		}
	}

	sort.Slice(spawnEggs, func(i, j int) bool {
		return spawnEggs[i].ItemID < spawnEggs[j].ItemID
	})

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/spawn_egg; DO NOT EDIT.\n\n")
	buf.WriteString("package spawnegg\n\n")

	buf.WriteString(fmt.Sprintf("const SpawnEggCount = %d\n\n", len(spawnEggs)))

	buf.WriteString("type SpawnEggInfo struct {\n")
	buf.WriteString("\tItemID     int32\n")
	buf.WriteString("\tItemName   string\n")
	buf.WriteString("\tEntityName string\n")
	buf.WriteString("}\n\n")

	buf.WriteString("var SpawnEggs = []SpawnEggInfo{\n")
	for _, egg := range spawnEggs {
		buf.WriteString(fmt.Sprintf("\t{ItemID: %d, ItemName: %q, EntityName: %q},\n",
			egg.ItemID, egg.ItemName, egg.EntityName))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var spawnEggByItem = map[string]string{\n")
	for _, egg := range spawnEggs {
		buf.WriteString(fmt.Sprintf("\t%q: %q,\n", egg.ItemName, egg.EntityName))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func EntityFromSpawnEgg(itemName string) string {
	return spawnEggByItem[itemName]
}

func IsSpawnEgg(itemName string) bool {
	_, ok := spawnEggByItem[itemName]
	return ok
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d spawn eggs)\n", outputFile, len(spawnEggs))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}
