//go:build ignore

package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

type trackedField struct {
	ClassName  string
	FieldName  string
	Serializer string
}

type classInfo struct {
	Name       string
	Parent     string
	Fields     []trackedField
	BaseOffset int
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	entityDir := filepath.Join(projectRoot, ".mc-decompiled", *version+"-decompiled", "net", "minecraft", "world", "entity")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "tracked_data", "tracked_data.go")

	classes, err := scanEntityClasses(entityDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "scan entity classes: %v\n", err)
		os.Exit(1)
	}

	// Compute cumulative offsets based on inheritance
	computeOffsets(classes)

	// Collect all fields
	var allFields []trackedField
	for _, c := range classes {
		allFields = append(allFields, c.Fields...)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/tracked_data; DO NOT EDIT.\n\n")
	buf.WriteString("package trackeddata\n\n")

	buf.WriteString(fmt.Sprintf("const TrackedDataFieldCount = %d\n\n", len(allFields)))

	// Sort classes alphabetically for output
	classNames := make([]string, 0, len(classes))
	for cn := range classes {
		classNames = append(classNames, cn)
	}
	sort.Strings(classNames)

	buf.WriteString("type TrackedDataField struct {\n")
	buf.WriteString("\tClassName  string\n")
	buf.WriteString("\tFieldName  string\n")
	buf.WriteString("\tSerializer string\n")
	buf.WriteString("\tIndex      byte\n")
	buf.WriteString("}\n\n")

	buf.WriteString("var TrackedDataFields = []TrackedDataField{\n")
	for _, cn := range classNames {
		c := classes[cn]
		for i, f := range c.Fields {
			idx := c.BaseOffset + i
			buf.WriteString(fmt.Sprintf("\t{%q, %q, %q, %d},\n", f.ClassName, f.FieldName, f.Serializer, idx))
		}
	}
	buf.WriteString("}\n\n")

	// Generate per-class constants with cumulative indices
	buf.WriteString("// Entity metadata indices (cumulative through inheritance chain)\n")
	for _, cn := range classNames {
		c := classes[cn]
		if len(c.Fields) == 0 {
			continue
		}
		buf.WriteString(fmt.Sprintf("\n// %s metadata indices", cn))
		if c.Parent != "" {
			buf.WriteString(fmt.Sprintf(" (extends %s, base offset %d)", c.Parent, c.BaseOffset))
		}
		buf.WriteString("\n")
		buf.WriteString("const (\n")
		for i, f := range c.Fields {
			constName := toConstName(f.FieldName)
			idx := c.BaseOffset + i
			buf.WriteString(fmt.Sprintf("\t%s%s byte = %d\n", cn, constName, idx))
		}
		buf.WriteString(")\n")
	}

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d tracked data fields from %d entity classes)\n", outputFile, len(allFields), len(classes))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func scanEntityClasses(dir string) (map[string]*classInfo, error) {
	classes := make(map[string]*classInfo)

	err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() || !strings.HasSuffix(info.Name(), ".java") {
			return nil
		}

		ci, err := parseEntityClass(path)
		if err != nil || ci == nil {
			return nil
		}
		if len(ci.Fields) > 0 {
			classes[ci.Name] = ci
		}
		return nil
	})

	return classes, err
}

func parseEntityClass(javaFile string) (*classInfo, error) {
	content, err := os.ReadFile(javaFile)
	if err != nil {
		return nil, err
	}

	text := string(content)

	// Extract class name and parent
	classPattern := regexp.MustCompile(`public (?:abstract )?class (\w+)(?:\s+extends\s+(\w+))?`)
	classMatch := classPattern.FindStringSubmatch(text)
	if len(classMatch) < 2 {
		return nil, nil
	}

	ci := &classInfo{
		Name: classMatch[1],
	}
	if len(classMatch) > 2 {
		ci.Parent = classMatch[2]
	}

	// Match: EntityDataAccessor<...> FIELD_NAME = SynchedEntityData.defineId(..., EntityDataSerializers.TYPE)
	// Use (?s) for DOTALL mode to match across newlines
	// Use .+? instead of [^>]+ to handle nested generics like Optional<Component>
	// Capture any uppercase identifier (some fields don't have DATA_ prefix, e.g. SLEEPING_POS_ID)
	pattern := regexp.MustCompile(`(?s)EntityDataAccessor<.+?>\s+([A-Z][A-Z0-9_]+)\s*=\s*SynchedEntityData\.defineId\([^,]+,\s*EntityDataSerializers\.(\w+)`)

	for _, match := range pattern.FindAllStringSubmatch(text, -1) {
		if len(match) > 2 {
			ci.Fields = append(ci.Fields, trackedField{
				ClassName:  ci.Name,
				FieldName:  match[1],
				Serializer: match[2],
			})
		}
	}

	return ci, nil
}

func computeOffsets(classes map[string]*classInfo) {
	// Compute base offset for each class based on parent's total field count
	computed := make(map[string]bool)

	var compute func(name string) int
	compute = func(name string) int {
		ci, ok := classes[name]
		if !ok {
			return 0
		}
		if computed[name] {
			return ci.BaseOffset + len(ci.Fields)
		}

		if ci.Parent != "" {
			ci.BaseOffset = compute(ci.Parent)
		}
		computed[name] = true
		return ci.BaseOffset + len(ci.Fields)
	}

	for name := range classes {
		compute(name)
	}
}

func toConstName(fieldName string) string {
	// DATA_SHARED_FLAGS_ID -> SharedFlagsId
	// SLEEPING_POS_ID -> SleepingPosId
	name := strings.TrimPrefix(fieldName, "DATA_")
	parts := strings.Split(strings.ToLower(name), "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}
