//go:build ignore

package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	javaFile := filepath.Join(projectRoot, ".mc-decompiled", *version+"-decompiled", "net", "minecraft", "world", "level", "block", "FlowerPotBlock.java")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "flower_pot", "flower_pots.go")

	pots, err := parseFlowerPotJava(javaFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse FlowerPotBlock.java: %v\n", err)
		os.Exit(1)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/flower_pot; DO NOT EDIT.\n\n")
	buf.WriteString("package flowerpot\n\n")

	buf.WriteString(fmt.Sprintf("const FlowerPotCount = %d\n\n", len(pots)))

	buf.WriteString("var FlowerPots = []string{\n")
	for _, p := range pots {
		buf.WriteString(fmt.Sprintf("\t%q,\n", p))
	}
	buf.WriteString("}\n")

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d flower pots)\n", outputFile, len(pots))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func parseFlowerPotJava(javaFile string) ([]string, error) {
	content, err := os.ReadFile(javaFile)
	if err != nil {
		return nil, err
	}

	// Match: Blocks.POTTED_... references
	pattern := regexp.MustCompile(`Blocks\.(POTTED_\w+)`)
	seen := make(map[string]bool)
	var pots []string

	for _, match := range pattern.FindAllStringSubmatch(string(content), -1) {
		if len(match) > 1 {
			name := "minecraft:" + strings.ToLower(match[1])
			if !seen[name] {
				seen[name] = true
				pots = append(pots, name)
			}
		}
	}

	return pots, nil
}
