package registry

import (
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"testing"

	genreg "github.com/vitismc/vitis/internal/data/generated/registry"
	"github.com/vitismc/vitis/internal/nbt"
)

func TestDumpEnchantmentNBT(t *testing.T) {
	data := genreg.ConfigRegistryData()
	enchEntries, ok := data["minecraft:enchantment"]
	if !ok {
		t.Fatal("no minecraft:enchantment in config data")
	}

	for _, entry := range enchEntries {
		if entry.Name != "minecraft:binding_curse" {
			continue
		}
		t.Logf("Entry: %s, %d bytes", entry.Name, len(entry.Data))
		t.Logf("Hex:\n%s", hex.Dump(entry.Data))

		// Verify first byte is TAG_Compound (0x0a)
		if len(entry.Data) < 1 || entry.Data[0] != 0x0a {
			t.Errorf("first byte is 0x%02x, expected 0x0a (TAG_Compound)", entry.Data[0])
		}
		return
	}
	t.Fatal("minecraft:binding_curse not found")
}

func TestDumpInstrumentNBT(t *testing.T) {
	data := genreg.ConfigRegistryData()
	instrEntries, ok := data["minecraft:instrument"]
	if !ok {
		t.Fatal("no minecraft:instrument in config data")
	}

	for _, entry := range instrEntries {
		if !strings.Contains(entry.Name, "admire") {
			continue
		}
		t.Logf("Entry: %s, %d bytes", entry.Name, len(entry.Data))
		t.Logf("Hex:\n%s", hex.Dump(entry.Data))
		return
	}
	t.Fatal("admire instrument not found")
}

func TestManualBindingCurseNBT(t *testing.T) {
	// Manually build the exact NBT we expect for binding_curse
	root := nbt.NewCompound()

	root.PutInt("anvil_cost", 8)

	desc := nbt.NewCompound()
	desc.PutString("translate", "enchantment.minecraft.binding_curse")
	root.PutCompound("description", desc)

	preventArmorChange := nbt.NewCompound() // empty
	effects := nbt.NewCompound()
	effects.PutCompound("minecraft:prevent_armor_change", preventArmorChange)
	root.PutCompound("effects", effects)

	maxCost := nbt.NewCompound()
	maxCost.PutInt("base", 50)
	maxCost.PutInt("per_level_above_first", 0)
	root.PutCompound("max_cost", maxCost)

	root.PutInt("max_level", 1)

	minCost := nbt.NewCompound()
	minCost.PutInt("base", 25)
	minCost.PutInt("per_level_above_first", 0)
	root.PutCompound("min_cost", minCost)

	slotsList := nbt.NewList(nbt.TagString)
	slotsList.Add("armor")
	root.PutList("slots", slotsList)

	root.PutString("supported_items", "#minecraft:enchantable/equippable")

	root.PutInt("weight", 1)

	enc := nbt.NewEncoder(256)
	if err := enc.WriteRootCompound(root); err != nil {
		t.Fatalf("encode manual NBT: %v", err)
	}
	manualBytes := enc.Bytes()

	// Now compare with generated
	data := genreg.ConfigRegistryData()
	enchEntries := data["minecraft:enchantment"]
	var genBytes []byte
	for _, entry := range enchEntries {
		if entry.Name == "minecraft:binding_curse" {
			genBytes = entry.Data
			break
		}
	}
	if genBytes == nil {
		t.Fatal("binding_curse not found in generated data")
	}

	t.Logf("Manual  (%d bytes):\n%s", len(manualBytes), hex.Dump(manualBytes))
	t.Logf("Generated (%d bytes):\n%s", len(genBytes), hex.Dump(genBytes))

	if len(manualBytes) != len(genBytes) {
		t.Errorf("length mismatch: manual=%d generated=%d", len(manualBytes), len(genBytes))
	}

	// Find first difference
	minLen := len(manualBytes)
	if len(genBytes) < minLen {
		minLen = len(genBytes)
	}
	for i := 0; i < minLen; i++ {
		if manualBytes[i] != genBytes[i] {
			t.Errorf("first difference at offset %d: manual=0x%02x generated=0x%02x", i, manualBytes[i], genBytes[i])
			break
		}
	}
}

func TestGeneratorJSONToNBTBindingCurse(t *testing.T) {
	// Read the actual JSON file and convert using the same logic as the generator
	jsonPath := "../../.mc1214-data/1.21.4/datapacks/enchantment/binding_curse.json"
	jsonData, err := os.ReadFile(jsonPath)
	if err != nil {
		t.Skipf("skip: %v", err)
	}

	var raw interface{}
	dec := json.NewDecoder(strings.NewReader(string(jsonData)))
	dec.UseNumber()
	if err := dec.Decode(&raw); err != nil {
		t.Fatalf("parse JSON: %v", err)
	}

	m, ok := raw.(map[string]interface{})
	if !ok {
		t.Fatalf("expected map, got %T", raw)
	}

	// Print all keys and their JSON types
	for k, v := range m {
		switch val := v.(type) {
		case json.Number:
			t.Logf("  %s: json.Number(%s)", k, val.String())
		case string:
			t.Logf("  %s: string(%q)", k, val)
		case bool:
			t.Logf("  %s: bool(%v)", k, val)
		case map[string]interface{}:
			t.Logf("  %s: object (keys: %v)", k, mapKeys(val))
		case []interface{}:
			t.Logf("  %s: array (len %d)", k, len(val))
		default:
			t.Logf("  %s: %T", k, v)
		}
	}

	// Now show the generated bytes
	data := genreg.ConfigRegistryData()
	for _, entry := range data["minecraft:enchantment"] {
		if entry.Name == "minecraft:binding_curse" {
			t.Logf("\nGenerated bytes (%d):\n%s", len(entry.Data), hex.Dump(entry.Data))
			break
		}
	}
}

func mapKeys(m map[string]interface{}) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	return keys
}

func TestCompareAllRegistries(t *testing.T) {
	data := genreg.ConfigRegistryData()
	for regName, entries := range data {
		t.Logf("%s: %d entries", regName, len(entries))
		if len(entries) > 0 {
			first := entries[0]
			t.Logf("  first entry: %s (%d bytes, starts with 0x%02x)", first.Name, len(first.Data), first.Data[0])
		}
	}
}

func TestDumpAllEnchantmentSizes(t *testing.T) {
	data := genreg.ConfigRegistryData()
	enchEntries := data["minecraft:enchantment"]
	for _, entry := range enchEntries {
		prefix := ""
		if len(entry.Data) > 0 {
			prefix = fmt.Sprintf("0x%02x", entry.Data[0])
		}
		t.Logf("  %s: %d bytes, first=%s", entry.Name, len(entry.Data), prefix)
	}
}
