//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type wolfVariantJSON struct {
	WildTexture  string `json:"wild_texture"`
	TameTexture  string `json:"tame_texture"`
	AngryTexture string `json:"angry_texture"`
	Biomes       any    `json:"biomes"`
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	datapackDir := filepath.Join(projectRoot, ".mcdata", *version, "datapacks", "wolf_variant")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "wolf_variant", "wolf_variants.go")

	entries, err := os.ReadDir(datapackDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read wolf_variant dir: %v\n", err)
		os.Exit(1)
	}

	type wolfEntry struct {
		Name        string
		WildTexture string
	}

	var wolves []wolfEntry
	for _, entry := range entries {
		if !strings.HasSuffix(entry.Name(), ".json") {
			continue
		}

		data, err := os.ReadFile(filepath.Join(datapackDir, entry.Name()))
		if err != nil {
			continue
		}

		var w wolfVariantJSON
		if err := json.Unmarshal(data, &w); err != nil {
			continue
		}

		name := "minecraft:" + strings.TrimSuffix(entry.Name(), ".json")
		wolves = append(wolves, wolfEntry{
			Name:        name,
			WildTexture: w.WildTexture,
		})
	}

	sort.Slice(wolves, func(i, j int) bool {
		return wolves[i].Name < wolves[j].Name
	})

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/wolf_variant; DO NOT EDIT.\n\n")
	buf.WriteString("package wolfvariant\n\n")

	buf.WriteString("type WolfVariantInfo struct {\n")
	buf.WriteString("\tID          int32\n")
	buf.WriteString("\tName        string\n")
	buf.WriteString("\tWildTexture string\n")
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("const WolfVariantCount = %d\n\n", len(wolves)))

	buf.WriteString("var WolfVariants = []WolfVariantInfo{\n")
	for i, w := range wolves {
		buf.WriteString(fmt.Sprintf("\t{ID: %d, Name: %q, WildTexture: %q},\n",
			i, w.Name, w.WildTexture))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var wolfVariantByName = map[string]int32{\n")
	for i, w := range wolves {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", w.Name, i))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func WolfVariantIDByName(name string) int32 {
	if id, ok := wolfVariantByName[name]; ok {
		return id
	}
	return -1
}

func WolfVariantByID(id int32) *WolfVariantInfo {
	if id < 0 || int(id) >= len(WolfVariants) {
		return nil
	}
	return &WolfVariants[id]
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d wolf variants)\n", outputFile, len(wolves))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}
