//go:build ignore

package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	javaFile := filepath.Join(projectRoot, ".mc-decompiled", *version+"-decompiled", "net", "minecraft", "sounds", "SoundSource.java")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "sound_category", "sound_categories.go")

	soundCategories, err := parseSoundSourceJava(javaFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse SoundSource.java: %v\n", err)
		os.Exit(1)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/sound_category; DO NOT EDIT.\n\n")
	buf.WriteString("package soundcategory\n\n")

	buf.WriteString(fmt.Sprintf("const SoundCategoryCount = %d\n\n", len(soundCategories)))

	buf.WriteString("const (\n")
	for i, cat := range soundCategories {
		constName := toConstName(cat)
		buf.WriteString(fmt.Sprintf("\tCategory%s int32 = %d\n", constName, i))
	}
	buf.WriteString(")\n\n")

	buf.WriteString("var SoundCategoryNames = []string{\n")
	for _, cat := range soundCategories {
		buf.WriteString(fmt.Sprintf("\t%q,\n", cat))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var soundCategoryByName = map[string]int32{\n")
	for i, cat := range soundCategories {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", cat, i))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func SoundCategoryIDByName(name string) int32 {
	if id, ok := soundCategoryByName[name]; ok {
		return id
	}
	return -1
}

func SoundCategoryNameByID(id int32) string {
	if id < 0 || int(id) >= len(SoundCategoryNames) {
		return ""
	}
	return SoundCategoryNames[id]
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d sound categories)\n", outputFile, len(soundCategories))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func toConstName(name string) string {
	parts := strings.Split(name, "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}

func parseSoundSourceJava(javaFile string) ([]string, error) {
	content, err := os.ReadFile(javaFile)
	if err != nil {
		return nil, err
	}

	// Match enum values like: MASTER("master"), MUSIC("music"), etc.
	pattern := regexp.MustCompile(`^\s+(\w+)\("([^"]+)"\)[,;]`)
	var categories []string

	for _, line := range strings.Split(string(content), "\n") {
		if matches := pattern.FindStringSubmatch(line); len(matches) > 2 {
			categories = append(categories, matches[2])
		}
	}

	return categories, nil
}
