//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	noiseDir := filepath.Join(projectRoot, ".mcdata", *version, "datapacks", "worldgen", "noise")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "noise_parameter", "noise.go")

	params, err := parseNoiseParams(noiseDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse noise params: %v\n", err)
		os.Exit(1)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/noise_parameter; DO NOT EDIT.\n\n")
	buf.WriteString("package noiseparameter\n\n")

	buf.WriteString(fmt.Sprintf("const NoiseParameterCount = %d\n\n", len(params)))

	buf.WriteString("var NoiseParameters = []string{\n")
	for _, p := range params {
		buf.WriteString(fmt.Sprintf("\t%q,\n", p))
	}
	buf.WriteString("}\n")

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d noise parameters)\n", outputFile, len(params))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func parseNoiseParams(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	var params []string
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".json") {
			continue
		}
		name := strings.TrimSuffix(e.Name(), ".json")
		
		data, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			continue
		}
		var noiseData struct {
			FirstOctave int `json:"firstOctave"`
		}
		if err := json.Unmarshal(data, &noiseData); err == nil {
			params = append(params, "minecraft:"+name)
		}
	}

	sort.Strings(params)
	return params, nil
}
