//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type registriesJSON map[string]registryDef

type registryDef struct {
	ProtocolID int                 `json:"protocol_id"`
	Entries    map[string]entryDef `json:"entries"`
}

type entryDef struct {
	ProtocolID int `json:"protocol_id"`
}

type frogEntry struct {
	Name string
	ID   int
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	inputFile := filepath.Join(projectRoot, ".mcdata", *version, "registries.json")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "frog_variant", "frog_variants.go")

	data, err := os.ReadFile(inputFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read registries.json: %v\n", err)
		os.Exit(1)
	}

	var registries registriesJSON
	if err := json.Unmarshal(data, &registries); err != nil {
		fmt.Fprintf(os.Stderr, "parse registries.json: %v\n", err)
		os.Exit(1)
	}

	registry, ok := registries["minecraft:frog_variant"]
	if !ok {
		fmt.Fprintf(os.Stderr, "minecraft:frog_variant registry not found\n")
		os.Exit(1)
	}

	var frogs []frogEntry
	for name, entry := range registry.Entries {
		frogs = append(frogs, frogEntry{Name: name, ID: entry.ProtocolID})
	}
	sort.Slice(frogs, func(i, j int) bool {
		return frogs[i].ID < frogs[j].ID
	})

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/frog_variant; DO NOT EDIT.\n\n")
	buf.WriteString("package frogvariant\n\n")

	buf.WriteString(fmt.Sprintf("const FrogVariantCount = %d\n\n", len(frogs)))

	buf.WriteString("const (\n")
	for _, f := range frogs {
		constName := toConstName(strings.TrimPrefix(f.Name, "minecraft:"))
		buf.WriteString(fmt.Sprintf("\tFrog%s int32 = %d\n", constName, f.ID))
	}
	buf.WriteString(")\n\n")

	buf.WriteString("var FrogVariantNames = []string{\n")
	for _, f := range frogs {
		buf.WriteString(fmt.Sprintf("\t%q, // %d\n", f.Name, f.ID))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var frogVariantByName = map[string]int32{\n")
	for _, f := range frogs {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", f.Name, f.ID))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func FrogVariantIDByName(name string) int32 {
	if id, ok := frogVariantByName[name]; ok {
		return id
	}
	return -1
}

func FrogVariantNameByID(id int32) string {
	if id < 0 || int(id) >= len(FrogVariantNames) {
		return ""
	}
	return FrogVariantNames[id]
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d frog variants)\n", outputFile, len(frogs))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func toConstName(name string) string {
	parts := strings.Split(name, "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}
