//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

type entityJSON struct {
	ID          int     `json:"id"`
	Name        string  `json:"name"`
	DisplayName string  `json:"displayName"`
	Width       float64 `json:"width"`
	Height      float64 `json:"height"`
	Type        string  `json:"type"`
	Category    string  `json:"category"`
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	inputFile := filepath.Join(projectRoot, ".mcdata", *version, "entities.json")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "entity", "entities.go")

	data, err := os.ReadFile(inputFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read entities.json: %v\n", err)
		os.Exit(1)
	}

	var entities []entityJSON
	if err := json.Unmarshal(data, &entities); err != nil {
		fmt.Fprintf(os.Stderr, "parse entities.json: %v\n", err)
		os.Exit(1)
	}

	code := generateCode(entities)

	formatted, err := format.Source([]byte(code))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d entities)\n", outputFile, len(entities))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func generateCode(entities []entityJSON) string {
	var buf strings.Builder

	buf.WriteString("// Code generated by internal/data/generator/entity; DO NOT EDIT.\n\n")
	buf.WriteString("package entity\n\n")

	buf.WriteString("type EntityInfo struct {\n")
	buf.WriteString("\tID       int32\n")
	buf.WriteString("\tName     string\n")
	buf.WriteString("\tWidth    float64\n")
	buf.WriteString("\tHeight   float64\n")
	buf.WriteString("\tType     string\n")
	buf.WriteString("\tCategory string\n")
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("const EntityCount = %d\n\n", len(entities)))

	buf.WriteString("const (\n")
	for _, e := range entities {
		constName := toConstName(e.Name)
		buf.WriteString(fmt.Sprintf("\tEntity%s int32 = %d\n", constName, e.ID))
	}
	buf.WriteString(")\n\n")

	buf.WriteString("var Entities = []EntityInfo{\n")
	for _, e := range entities {
		buf.WriteString(fmt.Sprintf("\t{ID: %d, Name: %q, Width: %v, Height: %v, Type: %q, Category: %q},\n",
			e.ID, e.Name, e.Width, e.Height, e.Type, e.Category))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var entityByName = map[string]*EntityInfo{\n")
	for i, e := range entities {
		buf.WriteString(fmt.Sprintf("\t%q: &Entities[%d],\n", e.Name, i))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var entityByID = map[int32]*EntityInfo{\n")
	for i, e := range entities {
		buf.WriteString(fmt.Sprintf("\t%d: &Entities[%d],\n", e.ID, i))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func EntityByName(name string) *EntityInfo {
	return entityByName[name]
}

func EntityByID(id int32) *EntityInfo {
	return entityByID[id]
}

func EntityIDByName(name string) int32 {
	if e := entityByName[name]; e != nil {
		return e.ID
	}
	return -1
}
`)

	return buf.String()
}

func toConstName(name string) string {
	parts := strings.Split(name, "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}
