//go:build ignore

package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

type fuelEntry struct {
	Item     string
	BurnTime int
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	javaFile := filepath.Join(projectRoot, ".mc-decompiled", *version+"-decompiled", "net", "minecraft", "world", "level", "block", "entity", "FuelValues.java")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "fuels", "fuels.go")

	fuels, err := parseFuelsJava(javaFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse FuelValues.java: %v\n", err)
		os.Exit(1)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/fuels; DO NOT EDIT.\n\n")
	buf.WriteString("package fuels\n\n")

	buf.WriteString(fmt.Sprintf("const FuelCount = %d\n\n", len(fuels)))

	buf.WriteString("var Fuels = map[string]int{\n")
	for _, f := range fuels {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", f.Item, f.BurnTime))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func GetBurnTime(item string) int {
	if time, ok := Fuels[item]; ok {
		return time
	}
	return 0
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d fuels)\n", outputFile, len(fuels))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func parseFuelsJava(javaFile string) ([]fuelEntry, error) {
	content, err := os.ReadFile(javaFile)
	if err != nil {
		return nil, err
	}

	text := string(content)
	var fuels []fuelEntry

	// Base burn time is 200 ($$2 in the Java code)
	baseBurnTime := 200

	// Match: .add(Items.X, $$2 * N) or .add(Blocks.X, $$2 * N)
	// Patterns: $$2 * 100, $$2 * 8 * 10, $$2 * 12, $$2 * 8, $$2 * 3 / 2, $$2 / 2, etc.
	itemPattern := regexp.MustCompile(`\.add\((Items|Blocks)\.(\w+),\s*([^)]+)\)`)

	for _, match := range itemPattern.FindAllStringSubmatch(text, -1) {
		if len(match) > 3 {
			itemName := "minecraft:" + toSnakeCase(match[2])
			expr := strings.TrimSpace(match[3])
			burnTime := evaluateExpr(expr, baseBurnTime)
			if burnTime > 0 {
				fuels = append(fuels, fuelEntry{Item: itemName, BurnTime: burnTime})
			}
		}
	}

	return fuels, nil
}

func toSnakeCase(s string) string {
	return strings.ToLower(s)
}

func evaluateExpr(expr string, base int) int {
	// Replace $$2 with base value
	expr = strings.ReplaceAll(expr, "$$2", strconv.Itoa(base))
	// Handle: 1 + $$2 / 3 or 1 + $$2 * 20
	expr = strings.ReplaceAll(expr, " ", "")

	// Simple expression evaluator for patterns like:
	// 200, 200*100, 200*8*10, 200*3/2, 200/2, 1+200/3, 1+200*20
	result := 0

	// Handle addition first (split by +)
	parts := strings.Split(expr, "+")
	for _, part := range parts {
		result += evaluateMulDiv(part)
	}

	return result
}

func evaluateMulDiv(expr string) int {
	result := 0
	op := '+'

	i := 0
	for i < len(expr) {
		if expr[i] >= '0' && expr[i] <= '9' {
			num := 0
			for i < len(expr) && expr[i] >= '0' && expr[i] <= '9' {
				num = num*10 + int(expr[i]-'0')
				i++
			}
			if op == '+' || op == '*' {
				if result == 0 && op == '+' {
					result = num
				} else if op == '*' {
					result *= num
				} else {
					result += num
				}
			} else if op == '/' {
				if num != 0 {
					result /= num
				}
			}
		} else if expr[i] == '*' {
			op = '*'
			i++
		} else if expr[i] == '/' {
			op = '/'
			i++
		} else {
			i++
		}
	}

	return result
}
