//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type instrumentJSON struct {
	SoundEvent   any     `json:"sound_event"`
	UseDuration  float64 `json:"use_duration"`
	Range        float64 `json:"range"`
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	datapackDir := filepath.Join(projectRoot, ".mcdata", *version, "datapacks", "instrument")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "instrument", "instruments.go")

	entries, err := os.ReadDir(datapackDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read instrument dir: %v\n", err)
		os.Exit(1)
	}

	type instrumentEntry struct {
		Name        string
		UseDuration float64
		Range       float64
	}

	var instruments []instrumentEntry
	for _, entry := range entries {
		if !strings.HasSuffix(entry.Name(), ".json") {
			continue
		}

		data, err := os.ReadFile(filepath.Join(datapackDir, entry.Name()))
		if err != nil {
			continue
		}

		var inst instrumentJSON
		if err := json.Unmarshal(data, &inst); err != nil {
			continue
		}

		name := "minecraft:" + strings.TrimSuffix(entry.Name(), ".json")
		instruments = append(instruments, instrumentEntry{
			Name:        name,
			UseDuration: inst.UseDuration,
			Range:       inst.Range,
		})
	}

	sort.Slice(instruments, func(i, j int) bool {
		return instruments[i].Name < instruments[j].Name
	})

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/instrument; DO NOT EDIT.\n\n")
	buf.WriteString("package instrument\n\n")

	buf.WriteString("type InstrumentInfo struct {\n")
	buf.WriteString("\tID          int32\n")
	buf.WriteString("\tName        string\n")
	buf.WriteString("\tUseDuration float64\n")
	buf.WriteString("\tRange       float64\n")
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("const InstrumentCount = %d\n\n", len(instruments)))

	buf.WriteString("var Instruments = []InstrumentInfo{\n")
	for i, inst := range instruments {
		buf.WriteString(fmt.Sprintf("\t{ID: %d, Name: %q, UseDuration: %v, Range: %v},\n",
			i, inst.Name, inst.UseDuration, inst.Range))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var instrumentByName = map[string]int32{\n")
	for i, inst := range instruments {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", inst.Name, i))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func InstrumentIDByName(name string) int32 {
	if id, ok := instrumentByName[name]; ok {
		return id
	}
	return -1
}

func InstrumentByID(id int32) *InstrumentInfo {
	if id < 0 || int(id) >= len(Instruments) {
		return nil
	}
	return &Instruments[id]
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d instruments)\n", outputFile, len(instruments))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}
