//go:build ignore

package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "item_id_remap", "remap.go")

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/item_id_remap; DO NOT EDIT.\n\n")
	buf.WriteString("package itemidremap\n\n")

	buf.WriteString("// ItemIDRemap maps old item IDs to new item IDs for version migration.\n")
	buf.WriteString("// This is a placeholder - actual remap data would be extracted from version-specific data.\n")
	buf.WriteString("var ItemIDRemap = map[int32]int32{}\n\n")

	buf.WriteString(`func RemapItemID(oldID int32) int32 {
	if newID, ok := ItemIDRemap[oldID]; ok {
		return newID
	}
	return oldID
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (item ID remap placeholder)\n", outputFile)
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}
