//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type damageTypeJSON struct {
	Exhaustion       float64 `json:"exhaustion"`
	MessageID        string  `json:"message_id"`
	Scaling          string  `json:"scaling"`
	Effects          string  `json:"effects,omitempty"`
	DeathMessageType string  `json:"death_message_type,omitempty"`
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	datapackDir := filepath.Join(projectRoot, ".mcdata", *version, "datapacks", "damage_type")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "damage_type", "damage_types.go")

	entries, err := os.ReadDir(datapackDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read damage_type dir: %v\n", err)
		os.Exit(1)
	}

	type damageEntry struct {
		Name       string
		Exhaustion float64
		MessageID  string
		Scaling    string
	}

	var damageTypes []damageEntry
	for _, entry := range entries {
		if !strings.HasSuffix(entry.Name(), ".json") {
			continue
		}

		data, err := os.ReadFile(filepath.Join(datapackDir, entry.Name()))
		if err != nil {
			continue
		}

		var dt damageTypeJSON
		if err := json.Unmarshal(data, &dt); err != nil {
			continue
		}

		name := "minecraft:" + strings.TrimSuffix(entry.Name(), ".json")
		damageTypes = append(damageTypes, damageEntry{
			Name:       name,
			Exhaustion: dt.Exhaustion,
			MessageID:  dt.MessageID,
			Scaling:    dt.Scaling,
		})
	}

	sort.Slice(damageTypes, func(i, j int) bool {
		return damageTypes[i].Name < damageTypes[j].Name
	})

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/damage_type; DO NOT EDIT.\n\n")
	buf.WriteString("package damagetype\n\n")

	buf.WriteString("type DamageTypeInfo struct {\n")
	buf.WriteString("\tID         int32\n")
	buf.WriteString("\tName       string\n")
	buf.WriteString("\tExhaustion float64\n")
	buf.WriteString("\tMessageID  string\n")
	buf.WriteString("\tScaling    string\n")
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("const DamageTypeCount = %d\n\n", len(damageTypes)))

	buf.WriteString("var DamageTypes = []DamageTypeInfo{\n")
	for i, dt := range damageTypes {
		buf.WriteString(fmt.Sprintf("\t{ID: %d, Name: %q, Exhaustion: %v, MessageID: %q, Scaling: %q},\n",
			i, dt.Name, dt.Exhaustion, dt.MessageID, dt.Scaling))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var damageTypeByName = map[string]int32{\n")
	for i, dt := range damageTypes {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", dt.Name, i))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func DamageTypeIDByName(name string) int32 {
	if id, ok := damageTypeByName[name]; ok {
		return id
	}
	return -1
}

func DamageTypeByID(id int32) *DamageTypeInfo {
	if id < 0 || int(id) >= len(DamageTypes) {
		return nil
	}
	return &DamageTypes[id]
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d damage types)\n", outputFile, len(damageTypes))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}
