//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

type particleJSON struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	inputFile := filepath.Join(projectRoot, ".mcdata", *version, "particles.json")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "particle", "particles.go")

	data, err := os.ReadFile(inputFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read particles.json: %v\n", err)
		os.Exit(1)
	}

	var particles []particleJSON
	if err := json.Unmarshal(data, &particles); err != nil {
		fmt.Fprintf(os.Stderr, "parse particles.json: %v\n", err)
		os.Exit(1)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/particle; DO NOT EDIT.\n\n")
	buf.WriteString("package particle\n\n")

	buf.WriteString(fmt.Sprintf("const ParticleCount = %d\n\n", len(particles)))

	buf.WriteString("const (\n")
	for _, p := range particles {
		constName := toConstName(p.Name)
		buf.WriteString(fmt.Sprintf("\tParticle%s int32 = %d\n", constName, p.ID))
	}
	buf.WriteString(")\n\n")

	buf.WriteString("var ParticleNames = []string{\n")
	for _, p := range particles {
		buf.WriteString(fmt.Sprintf("\t%q, // %d\n", p.Name, p.ID))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var particleByName = map[string]int32{\n")
	for _, p := range particles {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", p.Name, p.ID))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func ParticleIDByName(name string) int32 {
	if id, ok := particleByName[name]; ok {
		return id
	}
	return -1
}

func ParticleNameByID(id int32) string {
	if id < 0 || int(id) >= len(ParticleNames) {
		return ""
	}
	return ParticleNames[id]
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d particles)\n", outputFile, len(particles))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func toConstName(name string) string {
	parts := strings.Split(name, "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}
