//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	settingsDir := filepath.Join(projectRoot, ".mcdata", *version, "datapacks", "worldgen", "noise_settings")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "chunk_gen_settings", "settings.go")

	settings, err := parseSettings(settingsDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse noise settings: %v\n", err)
		os.Exit(1)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/chunk_gen_settings; DO NOT EDIT.\n\n")
	buf.WriteString("package chunkgensettings\n\n")

	buf.WriteString(fmt.Sprintf("const ChunkGenSettingsCount = %d\n\n", len(settings)))

	buf.WriteString("var ChunkGenSettings = []string{\n")
	for _, s := range settings {
		buf.WriteString(fmt.Sprintf("\t%q,\n", s))
	}
	buf.WriteString("}\n")

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d chunk gen settings)\n", outputFile, len(settings))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func parseSettings(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	var settings []string
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".json") {
			continue
		}
		name := strings.TrimSuffix(e.Name(), ".json")
		
		data, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			continue
		}
		var settingsData struct {
			SeaLevel int `json:"sea_level"`
		}
		if err := json.Unmarshal(data, &settingsData); err == nil {
			settings = append(settings, "minecraft:"+name)
		}
	}

	sort.Strings(settings)
	return settings, nil
}
