//go:build ignore

package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	javaFile := filepath.Join(projectRoot, ".mc-decompiled", *version+"-decompiled", "net", "minecraft", "network", "syncher", "EntityDataSerializers.java")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "meta_data_type", "meta_data_types.go")

	metaDataTypes, err := parseEntityDataSerializersJava(javaFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse EntityDataSerializers.java: %v\n", err)
		os.Exit(1)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/meta_data_type; DO NOT EDIT.\n\n")
	buf.WriteString("package metadatatype\n\n")

	buf.WriteString(fmt.Sprintf("const MetaDataTypeCount = %d\n\n", len(metaDataTypes)))

	buf.WriteString("const (\n")
	for _, mdt := range metaDataTypes {
		constName := toConstName(mdt.Name)
		buf.WriteString(fmt.Sprintf("\tType%s int32 = %d\n", constName, mdt.ID))
	}
	buf.WriteString(")\n\n")

	buf.WriteString("var MetaDataTypeNames = []string{\n")
	for _, mdt := range metaDataTypes {
		buf.WriteString(fmt.Sprintf("\t%q, // %d\n", mdt.Name, mdt.ID))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var metaDataTypeByName = map[string]int32{\n")
	for _, mdt := range metaDataTypes {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", mdt.Name, mdt.ID))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func MetaDataTypeIDByName(name string) int32 {
	if id, ok := metaDataTypeByName[name]; ok {
		return id
	}
	return -1
}

func MetaDataTypeNameByID(id int32) string {
	if id < 0 || int(id) >= len(MetaDataTypeNames) {
		return ""
	}
	return MetaDataTypeNames[id]
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d meta data types)\n", outputFile, len(metaDataTypes))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func toConstName(name string) string {
	parts := strings.Split(name, "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}

type metaDataTypeEntry struct {
	Name string
	ID   int
}

func parseEntityDataSerializersJava(javaFile string) ([]metaDataTypeEntry, error) {
	content, err := os.ReadFile(javaFile)
	if err != nil {
		return nil, err
	}

	// Parse static block to get registration order
	// Match: registerSerializer(BYTE); registerSerializer(INT); etc.
	staticPattern := regexp.MustCompile(`registerSerializer\((\w+)\);`)

	// Match field definitions: public static final EntityDataSerializer<...> BYTE = ...
	fieldPattern := regexp.MustCompile(`public static final EntityDataSerializer<[^>]+>\s+(\w+)\s*=`)

	lines := string(content)

	// First, extract all field names in order of appearance
	fieldMatches := fieldPattern.FindAllStringSubmatch(lines, -1)
	fieldOrder := make(map[string]int)
	for i, m := range fieldMatches {
		if len(m) > 1 {
			fieldOrder[m[1]] = i
		}
	}

	// Then, extract registration order from static block
	var result []metaDataTypeEntry
	staticMatches := staticPattern.FindAllStringSubmatch(lines, -1)
	for i, m := range staticMatches {
		if len(m) > 1 {
			name := normalizeTypeName(m[1])
			result = append(result, metaDataTypeEntry{Name: name, ID: i})
		}
	}

	return result, nil
}

func normalizeTypeName(s string) string {
	// Java constants are SCREAMING_SNAKE_CASE, just lowercase them
	return strings.ToLower(s)
}
