//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	featuresDir := filepath.Join(projectRoot, ".mcdata", *version, "datapacks", "worldgen", "placed_feature")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "placed_features", "features.go")

	features, err := parseFeatures(featuresDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse placed features: %v\n", err)
		os.Exit(1)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/placed_features; DO NOT EDIT.\n\n")
	buf.WriteString("package placedfeatures\n\n")

	buf.WriteString(fmt.Sprintf("const PlacedFeatureCount = %d\n\n", len(features)))

	buf.WriteString("var PlacedFeatures = []string{\n")
	for _, f := range features {
		buf.WriteString(fmt.Sprintf("\t%q,\n", f))
	}
	buf.WriteString("}\n")

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d placed features)\n", outputFile, len(features))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func parseFeatures(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	var features []string
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".json") {
			continue
		}
		name := strings.TrimSuffix(e.Name(), ".json")
		
		data, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			continue
		}
		var featureData struct {
			Feature string `json:"feature"`
		}
		if err := json.Unmarshal(data, &featureData); err == nil {
			features = append(features, "minecraft:"+name)
		}
	}

	sort.Strings(features)
	return features, nil
}
