//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type paintingJSON struct {
	Width  int `json:"width"`
	Height int `json:"height"`
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	datapackDir := filepath.Join(projectRoot, ".mcdata", *version, "datapacks", "painting_variant")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "painting_variant", "painting_variants.go")

	entries, err := os.ReadDir(datapackDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read painting_variant dir: %v\n", err)
		os.Exit(1)
	}

	type paintingEntry struct {
		Name   string
		Width  int
		Height int
	}

	var paintings []paintingEntry
	for _, entry := range entries {
		if !strings.HasSuffix(entry.Name(), ".json") {
			continue
		}

		data, err := os.ReadFile(filepath.Join(datapackDir, entry.Name()))
		if err != nil {
			continue
		}

		var p paintingJSON
		if err := json.Unmarshal(data, &p); err != nil {
			continue
		}

		name := "minecraft:" + strings.TrimSuffix(entry.Name(), ".json")
		paintings = append(paintings, paintingEntry{
			Name:   name,
			Width:  p.Width,
			Height: p.Height,
		})
	}

	sort.Slice(paintings, func(i, j int) bool {
		return paintings[i].Name < paintings[j].Name
	})

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/painting_variant; DO NOT EDIT.\n\n")
	buf.WriteString("package paintingvariant\n\n")

	buf.WriteString("type PaintingVariantInfo struct {\n")
	buf.WriteString("\tID     int32\n")
	buf.WriteString("\tName   string\n")
	buf.WriteString("\tWidth  int32\n")
	buf.WriteString("\tHeight int32\n")
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("const PaintingVariantCount = %d\n\n", len(paintings)))

	buf.WriteString("var PaintingVariants = []PaintingVariantInfo{\n")
	for i, p := range paintings {
		buf.WriteString(fmt.Sprintf("\t{ID: %d, Name: %q, Width: %d, Height: %d},\n",
			i, p.Name, p.Width, p.Height))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var paintingByName = map[string]int32{\n")
	for i, p := range paintings {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", p.Name, i))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func PaintingVariantIDByName(name string) int32 {
	if id, ok := paintingByName[name]; ok {
		return id
	}
	return -1
}

func PaintingVariantByID(id int32) *PaintingVariantInfo {
	if id < 0 || int(id) >= len(PaintingVariants) {
		return nil
	}
	return &PaintingVariants[id]
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d painting variants)\n", outputFile, len(paintings))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}
