//go:build ignore

package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "recipe_remainder", "remainders.go")

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/recipe_remainder; DO NOT EDIT.\n\n")
	buf.WriteString("package reciperemainder\n\n")

	buf.WriteString("// RecipeRemainders maps item IDs to their crafting remainder items.\n")
	buf.WriteString("// For example, a water bucket returns an empty bucket after crafting.\n")
	buf.WriteString("var RecipeRemainders = map[string]string{\n")
	buf.WriteString("\t\"minecraft:water_bucket\": \"minecraft:bucket\",\n")
	buf.WriteString("\t\"minecraft:lava_bucket\": \"minecraft:bucket\",\n")
	buf.WriteString("\t\"minecraft:milk_bucket\": \"minecraft:bucket\",\n")
	buf.WriteString("\t\"minecraft:powder_snow_bucket\": \"minecraft:bucket\",\n")
	buf.WriteString("\t\"minecraft:axolotl_bucket\": \"minecraft:bucket\",\n")
	buf.WriteString("\t\"minecraft:cod_bucket\": \"minecraft:bucket\",\n")
	buf.WriteString("\t\"minecraft:salmon_bucket\": \"minecraft:bucket\",\n")
	buf.WriteString("\t\"minecraft:tropical_fish_bucket\": \"minecraft:bucket\",\n")
	buf.WriteString("\t\"minecraft:pufferfish_bucket\": \"minecraft:bucket\",\n")
	buf.WriteString("\t\"minecraft:tadpole_bucket\": \"minecraft:bucket\",\n")
	buf.WriteString("}\n\n")

	buf.WriteString(`func GetRemainder(item string) string {
	if remainder, ok := RecipeRemainders[item]; ok {
		return remainder
	}
	return ""
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (recipe remainders)\n", outputFile)
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}
