//go:build ignore

package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	projectRoot := findProjectRoot()
	javaFile := filepath.Join(projectRoot, ".mc-decompiled", *version+"-decompiled", "net", "minecraft", "world", "level", "chunk", "status", "ChunkStatus.java")
	outputFile := filepath.Join(projectRoot, "internal", "data", "generated", "chunk_status", "chunk_status.go")

	chunkStatuses, err := parseChunkStatusJava(javaFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse ChunkStatus.java: %v\n", err)
		os.Exit(1)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by internal/data/generator/chunk_status; DO NOT EDIT.\n\n")
	buf.WriteString("package chunkstatus\n\n")

	buf.WriteString(fmt.Sprintf("const ChunkStatusCount = %d\n\n", len(chunkStatuses)))

	buf.WriteString("const (\n")
	for i, status := range chunkStatuses {
		name := strings.TrimPrefix(status, "minecraft:")
		constName := toConstName(name)
		buf.WriteString(fmt.Sprintf("\tStatus%s int32 = %d\n", constName, i))
	}
	buf.WriteString(")\n\n")

	buf.WriteString("var ChunkStatusNames = []string{\n")
	for _, status := range chunkStatuses {
		buf.WriteString(fmt.Sprintf("\t%q,\n", status))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var chunkStatusByName = map[string]int32{\n")
	for i, status := range chunkStatuses {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", status, i))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(`func ChunkStatusIDByName(name string) int32 {
	if id, ok := chunkStatusByName[name]; ok {
		return id
	}
	return -1
}

func ChunkStatusNameByID(id int32) string {
	if id < 0 || int(id) >= len(ChunkStatusNames) {
		return ""
	}
	return ChunkStatusNames[id]
}

func IsFull(id int32) bool {
	return id == StatusFull
}
`)

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d chunk statuses)\n", outputFile, len(chunkStatuses))
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	wd, _ := os.Getwd()
	return wd
}

func toConstName(name string) string {
	parts := strings.Split(name, "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}

func parseChunkStatusJava(javaFile string) ([]string, error) {
	content, err := os.ReadFile(javaFile)
	if err != nil {
		return nil, err
	}

	// Match: public static final ChunkStatus EMPTY = register("empty", ...)
	pattern := regexp.MustCompile(`public static final ChunkStatus (\w+) = register\("([^"]+)"`)
	var statuses []string

	for _, line := range strings.Split(string(content), "\n") {
		if matches := pattern.FindStringSubmatch(line); len(matches) > 2 {
			statuses = append(statuses, "minecraft:"+matches[2])
		}
	}

	return statuses, nil
}
