//go:build ignore

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type registriesJSON map[string]registryDef

type registryDef struct {
	ProtocolID int                 `json:"protocol_id"`
	Entries    map[string]entryDef `json:"entries"`
}

type entryDef struct {
	ProtocolID int `json:"protocol_id"`
}

var configRegistries = map[string]string{
	"minecraft:banner_pattern":   "banner_pattern",
	"minecraft:chat_type":        "chat_type",
	"minecraft:damage_type":      "damage_type",
	"minecraft:dimension_type":   "dimension_type",
	"minecraft:enchantment":      "enchantment",
	"minecraft:instrument":       "instrument",
	"minecraft:jukebox_song":     "jukebox_song",
	"minecraft:painting_variant": "painting_variant",
	"minecraft:trim_material":    "trim_material",
	"minecraft:trim_pattern":     "trim_pattern",
	"minecraft:wolf_variant":     "wolf_variant",
	"minecraft:worldgen/biome":   "worldgen/biome",
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	flag.Parse()

	rootDir := findProjectRoot()

	registriesPath := filepath.Join(rootDir, ".mcdata", *version, "registries.json")
	tagsDir := filepath.Join(rootDir, ".mcdata", *version, "tags")
	outDir := filepath.Join(rootDir, "internal", "data", "generated", "tag")

	os.MkdirAll(outDir, 0o755)

	regs := loadRegistries(registriesPath)
	generateTags(regs, tagsDir, outDir)

	log.Println("Tag generation complete.")
}

func findProjectRoot() string {
	dir, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			log.Fatal("could not find project root (no go.mod)")
		}
		dir = parent
	}
}

func loadRegistries(path string) registriesJSON {
	data, err := os.ReadFile(path)
	if err != nil {
		log.Fatalf("read registries.json: %v", err)
	}
	var regs registriesJSON
	if err := json.Unmarshal(data, &regs); err != nil {
		log.Fatalf("parse registries.json: %v", err)
	}
	return regs
}

func generateTags(regs registriesJSON, tagsDir string, outDir string) {
	if _, err := os.Stat(tagsDir); os.IsNotExist(err) {
		log.Printf("Tags directory %s not found, skipping tag generation", tagsDir)
		return
	}

	type registryTagData struct {
		registryName string
		tags         map[string][]int32
	}

	var allRegistryTags []registryTagData
	totalTags := 0

	topDirs, err := os.ReadDir(tagsDir)
	if err != nil {
		log.Fatalf("read tags dir: %v", err)
	}

	for _, d := range topDirs {
		if !d.IsDir() {
			continue
		}
		dirName := d.Name()
		if dirName == "worldgen" {
			wgPath := filepath.Join(tagsDir, "worldgen")
			wgDirs, err := os.ReadDir(wgPath)
			if err != nil {
				log.Fatalf("read worldgen tags dir: %v", err)
			}
			for _, wd := range wgDirs {
				if !wd.IsDir() {
					continue
				}
				regName := "minecraft:worldgen/" + wd.Name()
				tagDirPath := filepath.Join(wgPath, wd.Name())
				tags, count := generateTagsForRegistry(regs, tagsDir, regName, tagDirPath)
				if count > 0 {
					allRegistryTags = append(allRegistryTags, registryTagData{regName, tags})
					totalTags += count
				}
			}
		} else {
			regName := "minecraft:" + dirName
			tagDirPath := filepath.Join(tagsDir, dirName)
			tags, count := generateTagsForRegistry(regs, tagsDir, regName, tagDirPath)
			if count > 0 {
				allRegistryTags = append(allRegistryTags, registryTagData{regName, tags})
				totalTags += count
			}
		}
	}

	sort.Slice(allRegistryTags, func(i, j int) bool {
		return allRegistryTags[i].registryName < allRegistryTags[j].registryName
	})

	var b strings.Builder
	b.WriteString("// Code generated by internal/data/generator/tag. DO NOT EDIT.\n\n")
	b.WriteString("package tag\n\n")
	b.WriteString("// Data returns pre-computed tag ID mappings for all registries.\n")
	b.WriteString("// Outer key: registry name, inner key: tag name, value: sorted entry IDs.\n")
	b.WriteString("func Data() map[string]map[string][]int32 {\n")
	b.WriteString("\treturn map[string]map[string][]int32{\n")

	for _, rt := range allRegistryTags {
		if len(rt.tags) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\t\t%q: {\n", rt.registryName)
		tagNames := make([]string, 0, len(rt.tags))
		for tn := range rt.tags {
			tagNames = append(tagNames, tn)
		}
		sort.Strings(tagNames)
		for _, tn := range tagNames {
			ids := rt.tags[tn]
			fmt.Fprintf(&b, "\t\t\t%q: {", tn)
			for i, id := range ids {
				if i > 0 {
					b.WriteString(", ")
				}
				fmt.Fprintf(&b, "%d", id)
			}
			b.WriteString("},\n")
		}
		b.WriteString("\t\t},\n")
	}

	b.WriteString("\t}\n")
	b.WriteString("}\n")

	writeGoFile(filepath.Join(outDir, "tags.go"), b.String())
	log.Printf("Generated tags.go with %d registries, %d total tags", len(allRegistryTags), totalTags)
}

type tagJSON struct {
	Values []json.RawMessage `json:"values"`
}

func generateTagsForRegistry(regs registriesJSON, tagsDir string, registryName string, tagDirPath string) (map[string][]int32, int) {
	rawTags := make(map[string][]string)
	loadTagFiles(tagDirPath, "", rawTags)

	if len(rawTags) == 0 {
		return nil, 0
	}

	resolved := make(map[string][]string)
	resolving := make(map[string]bool)
	for tagName := range rawTags {
		resolveTag(tagName, rawTags, resolved, resolving)
	}

	nameToID := buildNameToIDMap(regs, registryName)
	if nameToID == nil {
		nameToID = buildConfigNameToIDMap(regs, registryName, tagsDir)
	}
	if nameToID == nil {
		return nil, 0
	}

	result := make(map[string][]int32, len(resolved))
	for tagName, entries := range resolved {
		var ids []int32
		for _, entry := range entries {
			if id, ok := nameToID[entry]; ok {
				ids = append(ids, int32(id))
			}
		}
		sort.Slice(ids, func(i, j int) bool { return ids[i] < ids[j] })
		ids = dedup(ids)
		if len(ids) > 0 {
			result["minecraft:"+tagName] = ids
		}
	}
	return result, len(result)
}

func buildConfigNameToIDMap(regs registriesJSON, registryName string, tagsDir string) map[string]int {
	subdir, ok := configRegistries[registryName]
	if !ok {
		return nil
	}
	datapacksDir := filepath.Join(filepath.Dir(tagsDir), "datapacks")
	dirPath := filepath.Join(datapacksDir, subdir)
	entryNames := resolveConfigEntryOrder(regs, registryName, dirPath)
	if len(entryNames) == 0 {
		return nil
	}
	m := make(map[string]int, len(entryNames))
	for i, name := range entryNames {
		m[name] = i
	}
	return m
}

func resolveConfigEntryOrder(regs registriesJSON, regName string, dirPath string) []string {
	if reg, ok := regs[regName]; ok {
		type idEntry struct {
			Name string
			ID   int
		}
		entries := make([]idEntry, 0, len(reg.Entries))
		for eName, eDef := range reg.Entries {
			entries = append(entries, idEntry{Name: eName, ID: eDef.ProtocolID})
		}
		sort.Slice(entries, func(i, j int) bool {
			return entries[i].ID < entries[j].ID
		})
		names := make([]string, len(entries))
		for i, e := range entries {
			names[i] = e.Name
		}
		return names
	}

	files, err := os.ReadDir(dirPath)
	if err != nil {
		return nil
	}
	var names []string
	for _, f := range files {
		if f.IsDir() || !strings.HasSuffix(f.Name(), ".json") {
			continue
		}
		baseName := strings.TrimSuffix(f.Name(), ".json")
		names = append(names, "minecraft:"+baseName)
	}
	sort.Strings(names)
	return names
}

func loadTagFiles(dir string, prefix string, out map[string][]string) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		log.Fatalf("read tag dir %s: %v", dir, err)
	}
	for _, e := range entries {
		if e.IsDir() {
			subPrefix := e.Name()
			if prefix != "" {
				subPrefix = prefix + "/" + e.Name()
			}
			loadTagFiles(filepath.Join(dir, e.Name()), subPrefix, out)
			continue
		}
		if !strings.HasSuffix(e.Name(), ".json") {
			continue
		}
		baseName := strings.TrimSuffix(e.Name(), ".json")
		tagName := baseName
		if prefix != "" {
			tagName = prefix + "/" + baseName
		}

		data, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			log.Fatalf("read tag file %s: %v", filepath.Join(dir, e.Name()), err)
		}

		var tj tagJSON
		if err := json.Unmarshal(data, &tj); err != nil {
			log.Fatalf("parse tag %s: %v", tagName, err)
		}

		var values []string
		for _, raw := range tj.Values {
			var s string
			if err := json.Unmarshal(raw, &s); err != nil {
				var obj struct {
					ID       string `json:"id"`
					Required bool   `json:"required"`
				}
				if err2 := json.Unmarshal(raw, &obj); err2 != nil {
					log.Fatalf("parse tag entry in %s: %v / %v", tagName, err, err2)
				}
				values = append(values, obj.ID)
				continue
			}
			values = append(values, s)
		}
		out[tagName] = values
	}
}

func resolveTag(name string, raw map[string][]string, resolved map[string][]string, resolving map[string]bool) []string {
	if res, ok := resolved[name]; ok {
		return res
	}
	if resolving[name] {
		return nil
	}
	resolving[name] = true

	entries := raw[name]
	var result []string
	for _, entry := range entries {
		if strings.HasPrefix(entry, "#") {
			refName := strings.TrimPrefix(entry, "#minecraft:")
			if refName == entry[1:] {
				refName = strings.TrimPrefix(entry, "#")
			}
			subEntries := resolveTag(refName, raw, resolved, resolving)
			result = append(result, subEntries...)
		} else {
			result = append(result, entry)
		}
	}

	resolved[name] = result
	delete(resolving, name)
	return result
}

func buildNameToIDMap(regs registriesJSON, registryName string) map[string]int {
	reg, ok := regs[registryName]
	if !ok {
		return nil
	}
	m := make(map[string]int, len(reg.Entries))
	for name, def := range reg.Entries {
		m[name] = def.ProtocolID
	}
	return m
}

func dedup(ids []int32) []int32 {
	if len(ids) <= 1 {
		return ids
	}
	result := ids[:1]
	for i := 1; i < len(ids); i++ {
		if ids[i] != ids[i-1] {
			result = append(result, ids[i])
		}
	}
	return result
}

func writeGoFile(path string, content string) {
	formatted, err := format.Source([]byte(content))
	if err != nil {
		log.Printf("WARNING: gofmt failed for %s: %v (writing unformatted)", path, err)
		formatted = []byte(content)
	}
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		log.Fatalf("write %s: %v", path, err)
	}
}
